package hibernate.entidades;
// Generated 30/03/2021 12:52:16 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpBanco generated by hbm2java
 */
@Entity
@Table(name = "tp_banco", schema = "public")
public class TpBanco implements java.io.Serializable {

	private Integer codBanc;
	private String codCortBanc;
	private String nomBanc;
	private Integer indVistClie;
	private Integer indVistAdmi;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;
	private Integer indTienCuenNego;

	public TpBanco() {
	}

	public TpBanco(Integer codBanc, String codCortBanc, String nomBanc, Integer indVistClie, Integer indVistAdmi,
			Integer indEsta, String usuApliCrea, Date fecCreaRegi, Integer indTienCuenNego) {
		this.codBanc = codBanc;
		this.codCortBanc = codCortBanc;
		this.nomBanc = nomBanc;
		this.indVistClie = indVistClie;
		this.indVistAdmi = indVistAdmi;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.indTienCuenNego = indTienCuenNego;
	}

	public TpBanco(Integer codBanc, String codCortBanc, String nomBanc, Integer indVistClie, Integer indVistAdmi,
			Integer indEsta, String usuApliCrea, Date fecCreaRegi, String usuApliModi, Date fecModiRegi,
			Integer indTienCuenNego) {
		this.codBanc = codBanc;
		this.codCortBanc = codCortBanc;
		this.nomBanc = nomBanc;
		this.indVistClie = indVistClie;
		this.indVistAdmi = indVistAdmi;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
		this.indTienCuenNego = indTienCuenNego;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_banc", unique = true, nullable = false)
	public Integer getCodBanc() {
		return this.codBanc;
	}

	public void setCodBanc(Integer codBanc) {
		this.codBanc = codBanc;
	}

	@Column(name = "cod_cort_banc", nullable = false, length = 20)
	public String getCodCortBanc() {
		return this.codCortBanc;
	}

	public void setCodCortBanc(String codCortBanc) {
		this.codCortBanc = codCortBanc;
	}

	@Column(name = "nom_banc", nullable = false, length = 50)
	public String getNomBanc() {
		return this.nomBanc;
	}

	public void setNomBanc(String nomBanc) {
		this.nomBanc = nomBanc;
	}

	@Column(name = "ind_vist_clie", nullable = false)
	public Integer getIndVistClie() {
		return this.indVistClie;
	}

	public void setIndVistClie(Integer indVistClie) {
		this.indVistClie = indVistClie;
	}

	@Column(name = "ind_vist_admi", nullable = false)
	public Integer getIndVistAdmi() {
		return this.indVistAdmi;
	}

	public void setIndVistAdmi(Integer indVistAdmi) {
		this.indVistAdmi = indVistAdmi;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

	@Column(name = "ind_tien_cuen_nego", nullable = false)
	public Integer getIndTienCuenNego() {
		return this.indTienCuenNego;
	}

	public void setIndTienCuenNego(Integer indTienCuenNego) {
		this.indTienCuenNego = indTienCuenNego;
	}

}
