package hibernate.entidades;
// Generated 08/05/2021 03:53:47 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TpClien generated by hbm2java
 */
@Entity
@Table(name = "tp_clien", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "cod_usua"))
public class TpClien implements java.io.Serializable {

	private Integer codClie;
	private TpActivEcono tpActivEcono;
	private TpDepar tpDepar;
	private TpDistr tpDistr;
	private TpPais tpPaisByCodPaisNaci;
	private TpPais tpPaisByCodPaisResi;
	private TpProvi tpProvi;
	private TpTipoDocumPerso tpTipoDocumPerso;
	private TpUsuar tpUsuar;
	private String valDocuPers;
	private Date fecNaci;
	private String valPrimNombPers;
	private String valSeguNombPers;
	private String valPrimApelPers;
	private String valSeguApelPers;
	private String valRazoSociPers;
	private String valDocuEmpr;
	private String valTelePers;
	private String valDirePers;
	private String valCiud;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;
	private Integer indPepo;
	private String valPepoInst;
	private String valPepoRol;
	private String valNombPerf;

	public TpClien() {
		tpDepar = new TpDepar();
		tpDistr = new TpDistr();
		tpPaisByCodPaisNaci = new TpPais();
		tpPaisByCodPaisResi = new TpPais();
		tpProvi = new TpProvi();
		tpTipoDocumPerso = new TpTipoDocumPerso();
		tpUsuar = new TpUsuar();
		tpActivEcono = new TpActivEcono();
	}

	public TpClien(Integer codClie, TpPais tpPaisByCodPaisNaci, TpPais tpPaisByCodPaisResi,
			TpTipoDocumPerso tpTipoDocumPerso, TpUsuar tpUsuar, String valDocuPers, Date fecNaci, String valTelePers,
			String valDirePers, Integer indEsta, String usuApliCrea, Date fecCreaRegi, Integer indPepo) {
		this.codClie = codClie;
		this.tpPaisByCodPaisNaci = tpPaisByCodPaisNaci;
		this.tpPaisByCodPaisResi = tpPaisByCodPaisResi;
		this.tpTipoDocumPerso = tpTipoDocumPerso;
		this.tpUsuar = tpUsuar;
		this.valDocuPers = valDocuPers;
		this.fecNaci = fecNaci;
		this.valTelePers = valTelePers;
		this.valDirePers = valDirePers;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.indPepo = indPepo;
	}

	public TpClien(Integer codClie, TpActivEcono tpActivEcono, TpDepar tpDepar, TpDistr tpDistr,
			TpPais tpPaisByCodPaisNaci, TpPais tpPaisByCodPaisResi, TpProvi tpProvi, TpTipoDocumPerso tpTipoDocumPerso,
			TpUsuar tpUsuar, String valDocuPers, Date fecNaci, String valPrimNombPers, String valSeguNombPers,
			String valPrimApelPers, String valSeguApelPers, String valRazoSociPers, String valDocuEmpr,
			String valTelePers, String valDirePers, String valCiud, Integer indEsta, String usuApliCrea,
			Date fecCreaRegi, String usuApliModi, Date fecModiRegi, Integer indPepo, String valPepoInst,
			String valPepoRol, String valNombPerf) {
		this.codClie = codClie;
		this.tpActivEcono = tpActivEcono;
		this.tpDepar = tpDepar;
		this.tpDistr = tpDistr;
		this.tpPaisByCodPaisNaci = tpPaisByCodPaisNaci;
		this.tpPaisByCodPaisResi = tpPaisByCodPaisResi;
		this.tpProvi = tpProvi;
		this.tpTipoDocumPerso = tpTipoDocumPerso;
		this.tpUsuar = tpUsuar;
		this.valDocuPers = valDocuPers;
		this.fecNaci = fecNaci;
		this.valPrimNombPers = valPrimNombPers;
		this.valSeguNombPers = valSeguNombPers;
		this.valPrimApelPers = valPrimApelPers;
		this.valSeguApelPers = valSeguApelPers;
		this.valRazoSociPers = valRazoSociPers;
		this.valDocuEmpr = valDocuEmpr;
		this.valTelePers = valTelePers;
		this.valDirePers = valDirePers;
		this.valCiud = valCiud;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
		this.indPepo = indPepo;
		this.valPepoInst = valPepoInst;
		this.valPepoRol = valPepoRol;
		this.valNombPerf = valNombPerf;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_clie", unique = true, nullable = false)
	public Integer getCodClie() {
		return this.codClie;
	}

	public void setCodClie(Integer codClie) {
		this.codClie = codClie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_acti_econ")
	public TpActivEcono getTpActivEcono() {
		return this.tpActivEcono;
	}

	public void setTpActivEcono(TpActivEcono tpActivEcono) {
		this.tpActivEcono = tpActivEcono;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_depa_resi")
	public TpDepar getTpDepar() {
		return this.tpDepar;
	}

	public void setTpDepar(TpDepar tpDepar) {
		this.tpDepar = tpDepar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_dist_resi")
	public TpDistr getTpDistr() {
		return this.tpDistr;
	}

	public void setTpDistr(TpDistr tpDistr) {
		this.tpDistr = tpDistr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_pais_naci", nullable = false)
	public TpPais getTpPaisByCodPaisNaci() {
		return this.tpPaisByCodPaisNaci;
	}

	public void setTpPaisByCodPaisNaci(TpPais tpPaisByCodPaisNaci) {
		this.tpPaisByCodPaisNaci = tpPaisByCodPaisNaci;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_pais_resi", nullable = false)
	public TpPais getTpPaisByCodPaisResi() {
		return this.tpPaisByCodPaisResi;
	}

	public void setTpPaisByCodPaisResi(TpPais tpPaisByCodPaisResi) {
		this.tpPaisByCodPaisResi = tpPaisByCodPaisResi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_prov_resi")
	public TpProvi getTpProvi() {
		return this.tpProvi;
	}

	public void setTpProvi(TpProvi tpProvi) {
		this.tpProvi = tpProvi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tipo_docu_pers", nullable = false)
	public TpTipoDocumPerso getTpTipoDocumPerso() {
		return this.tpTipoDocumPerso;
	}

	public void setTpTipoDocumPerso(TpTipoDocumPerso tpTipoDocumPerso) {
		this.tpTipoDocumPerso = tpTipoDocumPerso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_usua", unique = true, nullable = false)
	public TpUsuar getTpUsuar() {
		return this.tpUsuar;
	}

	public void setTpUsuar(TpUsuar tpUsuar) {
		this.tpUsuar = tpUsuar;
	}

	@Column(name = "val_docu_pers", length = 50)
	public String getValDocuPers() {
		return this.valDocuPers;
	}

	public void setValDocuPers(String valDocuPers) {
		this.valDocuPers = valDocuPers;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_naci", length = 29)
	public Date getFecNaci() {
		return this.fecNaci;
	}

	public void setFecNaci(Date fecNaci) {
		this.fecNaci = fecNaci;
	}

	@Column(name = "val_prim_nomb_pers", length = 100)
	public String getValPrimNombPers() {
		return this.valPrimNombPers;
	}

	public void setValPrimNombPers(String valPrimNombPers) {
		this.valPrimNombPers = valPrimNombPers;
	}

	@Column(name = "val_segu_nomb_pers", length = 100)
	public String getValSeguNombPers() {
		return this.valSeguNombPers;
	}

	public void setValSeguNombPers(String valSeguNombPers) {
		this.valSeguNombPers = valSeguNombPers;
	}

	@Column(name = "val_prim_apel_pers", length = 100)
	public String getValPrimApelPers() {
		return this.valPrimApelPers;
	}

	public void setValPrimApelPers(String valPrimApelPers) {
		this.valPrimApelPers = valPrimApelPers;
	}

	@Column(name = "val_segu_apel_pers", length = 100)
	public String getValSeguApelPers() {
		return this.valSeguApelPers;
	}

	public void setValSeguApelPers(String valSeguApelPers) {
		this.valSeguApelPers = valSeguApelPers;
	}

	@Column(name = "val_razo_soci_pers", length = 200)
	public String getValRazoSociPers() {
		return this.valRazoSociPers;
	}

	public void setValRazoSociPers(String valRazoSociPers) {
		this.valRazoSociPers = valRazoSociPers;
	}

	@Column(name = "val_docu_empr", length = 50)
	public String getValDocuEmpr() {
		return this.valDocuEmpr;
	}

	public void setValDocuEmpr(String valDocuEmpr) {
		this.valDocuEmpr = valDocuEmpr;
	}

	@Column(name = "val_tele_pers", length = 20)
	public String getValTelePers() {
		return this.valTelePers;
	}

	public void setValTelePers(String valTelePers) {
		this.valTelePers = valTelePers;
	}

	@Column(name = "val_dire_pers", length = 200)
	public String getValDirePers() {
		return this.valDirePers;
	}

	public void setValDirePers(String valDirePers) {
		this.valDirePers = valDirePers;
	}

	@Column(name = "val_ciud", length = 50)
	public String getValCiud() {
		return this.valCiud;
	}

	public void setValCiud(String valCiud) {
		this.valCiud = valCiud;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

	@Column(name = "ind_pepo", nullable = false)
	public Integer getIndPepo() {
		return this.indPepo;
	}

	public void setIndPepo(Integer indPepo) {
		this.indPepo = indPepo;
	}

	@Column(name = "val_pepo_inst", length = 250)
	public String getValPepoInst() {
		return this.valPepoInst;
	}

	public void setValPepoInst(String valPepoInst) {
		this.valPepoInst = valPepoInst;
	}

	@Column(name = "val_pepo_rol", length = 250)
	public String getValPepoRol() {
		return this.valPepoRol;
	}

	public void setValPepoRol(String valPepoRol) {
		this.valPepoRol = valPepoRol;
	}

	@Column(name = "val_nomb_perf", length = 100)
	public String getValNombPerf() {
		return this.valNombPerf;
	}

	public void setValNombPerf(String valNombPerf) {
		this.valNombPerf = valNombPerf;
	}

}
