package hibernate.entidades;
// Generated 12/09/2019 12:32:03 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpEstadOpera generated by hbm2java
 */
@Entity
@Table(name = "tp_estad_opera", schema = "public")
public class TpEstadOpera implements java.io.Serializable {

	private Integer codEstaOper;
	private String desEstaOper;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpEstadOpera() {
	}

	public TpEstadOpera(Integer codEstaOper, String desEstaOper, Integer indEsta, String usuApliCrea,
			Date fecCreaRegi) {
		this.codEstaOper = codEstaOper;
		this.desEstaOper = desEstaOper;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpEstadOpera(Integer codEstaOper, String desEstaOper, Integer indEsta, String usuApliCrea, Date fecCreaRegi,
			String usuApliModi, Date fecModiRegi) {
		this.codEstaOper = codEstaOper;
		this.desEstaOper = desEstaOper;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_esta_oper", unique = true, nullable = false)
	public Integer getCodEstaOper() {
		return this.codEstaOper;
	}

	public void setCodEstaOper(Integer codEstaOper) {
		this.codEstaOper = codEstaOper;
	}

	@Column(name = "des_esta_oper", nullable = false, length = 50)
	public String getDesEstaOper() {
		return this.desEstaOper;
	}

	public void setDesEstaOper(String desEstaOper) {
		this.desEstaOper = desEstaOper;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
