package hibernate.entidades;
// Generated 14 ago. 2022 14:52:21 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpFactuSerieCorre generated by hbm2java
 */
@Entity
@Table(name = "tp_factu_serie_corre", schema = "public")
public class TpFactuSerieCorre implements java.io.Serializable {

	private Integer codSeriCorr;
	private TpFactuTipoDocumElect tpFactuTipoDocumElect;
	private String valSeri;
	private Integer valCorrInic;
	private Integer valCorrUsadUlti;
	private short indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpFactuSerieCorre() {
	}

	public TpFactuSerieCorre(Integer codSeriCorr, TpFactuTipoDocumElect tpFactuTipoDocumElect, String valSeri,
			Integer valCorrInic, Integer valCorrUsadUlti, short indEsta, String usuApliCrea, Date fecCreaRegi) {
		this.codSeriCorr = codSeriCorr;
		this.tpFactuTipoDocumElect = tpFactuTipoDocumElect;
		this.valSeri = valSeri;
		this.valCorrInic = valCorrInic;
		this.valCorrUsadUlti = valCorrUsadUlti;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpFactuSerieCorre(Integer codSeriCorr, TpFactuTipoDocumElect tpFactuTipoDocumElect, String valSeri,
			Integer valCorrInic, Integer valCorrUsadUlti, short indEsta, String usuApliCrea, Date fecCreaRegi,
			String usuApliModi, Date fecModiRegi) {
		this.codSeriCorr = codSeriCorr;
		this.tpFactuTipoDocumElect = tpFactuTipoDocumElect;
		this.valSeri = valSeri;
		this.valCorrInic = valCorrInic;
		this.valCorrUsadUlti = valCorrUsadUlti;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_seri_corr", unique = true, nullable = false)
	public Integer getCodSeriCorr() {
		return this.codSeriCorr;
	}

	public void setCodSeriCorr(Integer codSeriCorr) {
		this.codSeriCorr = codSeriCorr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tipo_docu_elec", nullable = false)
	public TpFactuTipoDocumElect getTpFactuTipoDocumElect() {
		return this.tpFactuTipoDocumElect;
	}

	public void setTpFactuTipoDocumElect(TpFactuTipoDocumElect tpFactuTipoDocumElect) {
		this.tpFactuTipoDocumElect = tpFactuTipoDocumElect;
	}

	@Column(name = "val_seri", nullable = false, length = 4)
	public String getValSeri() {
		return this.valSeri;
	}

	public void setValSeri(String valSeri) {
		this.valSeri = valSeri;
	}

	@Column(name = "val_corr_inic", nullable = false)
	public Integer getValCorrInic() {
		return this.valCorrInic;
	}

	public void setValCorrInic(Integer valCorrInic) {
		this.valCorrInic = valCorrInic;
	}

	@Column(name = "val_corr_usad_ulti", nullable = false)
	public Integer getValCorrUsadUlti() {
		return this.valCorrUsadUlti;
	}

	public void setValCorrUsadUlti(Integer valCorrUsadUlti) {
		this.valCorrUsadUlti = valCorrUsadUlti;
	}

	@Column(name = "ind_esta", nullable = false)
	public short getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(short indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
