package hibernate.entidades;
// Generated 08/05/2021 03:53:47 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpOrigeFondo generated by hbm2java
 */
@Entity
@Table(name = "tp_orige_fondo", schema = "public")
public class TpOrigeFondo implements java.io.Serializable {

	private Integer codOrigFond;
	private String desOrigFond;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpOrigeFondo() {
	}

	public TpOrigeFondo(Integer codOrigFond, String desOrigFond, Integer indEsta, String usuApliCrea,
			Date fecCreaRegi) {
		this.codOrigFond = codOrigFond;
		this.desOrigFond = desOrigFond;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpOrigeFondo(Integer codOrigFond, String desOrigFond, Integer indEsta, String usuApliCrea, Date fecCreaRegi,
			String usuApliModi, Date fecModiRegi) {
		this.codOrigFond = codOrigFond;
		this.desOrigFond = desOrigFond;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_orig_fond", unique = true, nullable = false)
	public Integer getCodOrigFond() {
		return this.codOrigFond;
	}

	public void setCodOrigFond(Integer codOrigFond) {
		this.codOrigFond = codOrigFond;
	}

	@Column(name = "des_orig_fond", nullable = false, length = 100)
	public String getDesOrigFond() {
		return this.desOrigFond;
	}

	public void setDesOrigFond(String desOrigFond) {
		this.desOrigFond = desOrigFond;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
