package hibernate.entidades;
// Generated 12/09/2019 12:32:03 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpParamGener generated by hbm2java
 */
@Entity
@Table(name = "tp_param_gener", schema = "public")
public class TpParamGener implements java.io.Serializable {

	private Integer codParaGene;
	private String nomParaGene;
	private String valParaGene;
	private String desValoParaGene;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpParamGener() {
	}

	public TpParamGener(Integer codParaGene, String nomParaGene, String valParaGene, String desValoParaGene,
			Integer indEsta, String usuApliCrea, Date fecCreaRegi) {
		this.codParaGene = codParaGene;
		this.nomParaGene = nomParaGene;
		this.valParaGene = valParaGene;
		this.desValoParaGene = desValoParaGene;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpParamGener(Integer codParaGene, String nomParaGene, String valParaGene, String desValoParaGene,
			Integer indEsta, String usuApliCrea, Date fecCreaRegi, String usuApliModi, Date fecModiRegi) {
		this.codParaGene = codParaGene;
		this.nomParaGene = nomParaGene;
		this.valParaGene = valParaGene;
		this.desValoParaGene = desValoParaGene;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_para_gene", unique = true, nullable = false)
	public Integer getCodParaGene() {
		return this.codParaGene;
	}

	public void setCodParaGene(Integer codParaGene) {
		this.codParaGene = codParaGene;
	}

	@Column(name = "nom_para_gene", nullable = false, length = 50)
	public String getNomParaGene() {
		return this.nomParaGene;
	}

	public void setNomParaGene(String nomParaGene) {
		this.nomParaGene = nomParaGene;
	}

	@Column(name = "val_para_gene", nullable = false, length = 20)
	public String getValParaGene() {
		return this.valParaGene;
	}

	public void setValParaGene(String valParaGene) {
		this.valParaGene = valParaGene;
	}

	@Column(name = "des_valo_para_gene", nullable = false, length = 300)
	public String getDesValoParaGene() {
		return this.desValoParaGene;
	}

	public void setDesValoParaGene(String desValoParaGene) {
		this.desValoParaGene = desValoParaGene;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
