package hibernate.entidades;
// Generated 12/09/2019 12:32:03 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TpTipoCambi generated by hbm2java
 */
@Entity
@Table(name = "tp_tipo_cambi", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "cod_divi",
		"cod_divi_camb" }))
public class TpTipoCambi implements java.io.Serializable {

	private Integer codTipoCamb;
	private TpDivis tpDivisByCodDiviCamb;
	private TpDivis tpDivisByCodDivi;
	private Double valCambComp;
	private Double valCambVent;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpTipoCambi() {
		tpDivisByCodDivi = new TpDivis();
		tpDivisByCodDiviCamb = new TpDivis();
	}

	public TpTipoCambi(Integer codTipoCamb, TpDivis tpDivisByCodDiviCamb, TpDivis tpDivisByCodDivi, Double valCambComp,
			Double valCambVent, Integer indEsta, String usuApliCrea, Date fecCreaRegi) {
		this.codTipoCamb = codTipoCamb;
		this.tpDivisByCodDiviCamb = tpDivisByCodDiviCamb;
		this.tpDivisByCodDivi = tpDivisByCodDivi;
		this.valCambComp = valCambComp;
		this.valCambVent = valCambVent;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpTipoCambi(Integer codTipoCamb, TpDivis tpDivisByCodDiviCamb, TpDivis tpDivisByCodDivi, Double valCambComp,
			Double valCambVent, Integer indEsta, String usuApliCrea, Date fecCreaRegi, String usuApliModi,
			Date fecModiRegi) {
		this.codTipoCamb = codTipoCamb;
		this.tpDivisByCodDiviCamb = tpDivisByCodDiviCamb;
		this.tpDivisByCodDivi = tpDivisByCodDivi;
		this.valCambComp = valCambComp;
		this.valCambVent = valCambVent;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_tipo_camb", unique = true, nullable = false)
	public Integer getCodTipoCamb() {
		return this.codTipoCamb;
	}

	public void setCodTipoCamb(Integer codTipoCamb) {
		this.codTipoCamb = codTipoCamb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_divi_camb", nullable = false)
	public TpDivis getTpDivisByCodDiviCamb() {
		return this.tpDivisByCodDiviCamb;
	}

	public void setTpDivisByCodDiviCamb(TpDivis tpDivisByCodDiviCamb) {
		this.tpDivisByCodDiviCamb = tpDivisByCodDiviCamb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_divi", nullable = false)
	public TpDivis getTpDivisByCodDivi() {
		return this.tpDivisByCodDivi;
	}

	public void setTpDivisByCodDivi(TpDivis tpDivisByCodDivi) {
		this.tpDivisByCodDivi = tpDivisByCodDivi;
	}

	@Column(name = "val_camb_comp", nullable = false, precision = 17, scale = 17)
	public Double getValCambComp() {
		return this.valCambComp;
	}

	public void setValCambComp(Double valCambComp) {
		this.valCambComp = valCambComp;
	}

	@Column(name = "val_camb_vent", nullable = false, precision = 17, scale = 17)
	public Double getValCambVent() {
		return this.valCambVent;
	}

	public void setValCambVent(Double valCambVent) {
		this.valCambVent = valCambVent;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
