package hibernate.entidades;
// Generated 30 jul. 2021 23:58:21 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpTipoPregu generated by hbm2java
 */
@Entity
@Table(name = "tp_tipo_pregu", schema = "public")
public class TpTipoPregu implements java.io.Serializable {

	private Integer codTipoPreg;
	private String desTipoPreg;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpTipoPregu() {
	}

	public TpTipoPregu(Integer codTipoPreg, String desTipoPreg, Integer indEsta, String usuApliCrea, Date fecCreaRegi) {
		this.codTipoPreg = codTipoPreg;
		this.desTipoPreg = desTipoPreg;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpTipoPregu(Integer codTipoPreg, String desTipoPreg, Integer indEsta, String usuApliCrea, Date fecCreaRegi,
			String usuApliModi, Date fecModiRegi) {
		this.codTipoPreg = codTipoPreg;
		this.desTipoPreg = desTipoPreg;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id

	@Column(name = "cod_tipo_preg", unique = true, nullable = false)
	public Integer getCodTipoPreg() {
		return this.codTipoPreg;
	}

	public void setCodTipoPreg(Integer codTipoPreg) {
		this.codTipoPreg = codTipoPreg;
	}

	@Column(name = "des_tipo_preg", nullable = false, length = 50)
	public String getDesTipoPreg() {
		return this.desTipoPreg;
	}

	public void setDesTipoPreg(String desTipoPreg) {
		this.desTipoPreg = desTipoPreg;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
