package hibernate.entidades;
// Generated 08/05/2021 03:53:47 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TpUsuar generated by hbm2java
 */
@Entity
@Table(name = "tp_usuar", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "ide_usua_emai"))
public class TpUsuar implements java.io.Serializable {

	private Integer codUsua;
	private TpTipoPerso tpTipoPerso;
	private String ideUsuaEmai;
	private String emaUsuaAuxi;
	private String codClav;
	private String valNomb;
	private Integer indCompDato;
	private Integer codClie;
	private Integer codEstaOper;
	private Integer codOperClie;
	private Integer codPerfUsua;
	private Date fecUltiModiClav;
	private Date fecUltiAcce;
	private Integer codEstaCuenUsua;
	private String valTokeCuen;
	private Date fecCreaToke;
	private String valTokeRestCuen;
	private Date fecCreaTokeRestCuen;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;
	private String valNombRegi;
	private Integer codUsuaPadr;

	public TpUsuar() {
		tpTipoPerso = new TpTipoPerso();
	}

	public TpUsuar(Integer codUsua, TpTipoPerso tpTipoPerso, String ideUsuaEmai, String codClav, Integer indCompDato,
			Integer codPerfUsua, Integer indEsta, String usuApliCrea, Date fecCreaRegi) {
		this.codUsua = codUsua;
		this.tpTipoPerso = tpTipoPerso;
		this.ideUsuaEmai = ideUsuaEmai;
		this.codClav = codClav;
		this.indCompDato = indCompDato;
		this.codPerfUsua = codPerfUsua;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpUsuar(Integer codUsua, TpTipoPerso tpTipoPerso, String ideUsuaEmai, String emaUsuaAuxi, String codClav,
			String valNomb, Integer indCompDato, Integer codClie, Integer codEstaOper, Integer codOperClie,
			Integer codPerfUsua, Date fecUltiModiClav, Date fecUltiAcce, Integer codEstaCuenUsua, String valTokeCuen,
			Date fecCreaToke, String valTokeRestCuen, Date fecCreaTokeRestCuen, Integer indEsta, String usuApliCrea,
			Date fecCreaRegi, String usuApliModi, Date fecModiRegi, String valNombRegi, Integer codUsuaPadr) {
		this.codUsua = codUsua;
		this.tpTipoPerso = tpTipoPerso;
		this.ideUsuaEmai = ideUsuaEmai;
		this.emaUsuaAuxi = emaUsuaAuxi;
		this.codClav = codClav;
		this.valNomb = valNomb;
		this.indCompDato = indCompDato;
		this.codClie = codClie;
		this.codEstaOper = codEstaOper;
		this.codOperClie = codOperClie;
		this.codPerfUsua = codPerfUsua;
		this.fecUltiModiClav = fecUltiModiClav;
		this.fecUltiAcce = fecUltiAcce;
		this.codEstaCuenUsua = codEstaCuenUsua;
		this.valTokeCuen = valTokeCuen;
		this.fecCreaToke = fecCreaToke;
		this.valTokeRestCuen = valTokeRestCuen;
		this.fecCreaTokeRestCuen = fecCreaTokeRestCuen;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
		this.valNombRegi = valNombRegi;
		this.codUsuaPadr = codUsuaPadr;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_usua", unique = true, nullable = false)
	public Integer getCodUsua() {
		return this.codUsua;
	}

	public void setCodUsua(Integer codUsua) {
		this.codUsua = codUsua;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tipo_pers", nullable = false)
	public TpTipoPerso getTpTipoPerso() {
		return this.tpTipoPerso;
	}

	public void setTpTipoPerso(TpTipoPerso tpTipoPerso) {
		this.tpTipoPerso = tpTipoPerso;
	}

	@Column(name = "ide_usua_emai", unique = true, length = 100)
	public String getIdeUsuaEmai() {
		return this.ideUsuaEmai;
	}

	public void setIdeUsuaEmai(String ideUsuaEmai) {
		this.ideUsuaEmai = ideUsuaEmai;
	}

	@Column(name = "ema_usua_auxi", length = 100)
	public String getEmaUsuaAuxi() {
		return this.emaUsuaAuxi;
	}

	public void setEmaUsuaAuxi(String emaUsuaAuxi) {
		this.emaUsuaAuxi = emaUsuaAuxi;
	}

	@Column(name = "cod_clav", length = 32)
	public String getCodClav() {
		return this.codClav;
	}

	public void setCodClav(String codClav) {
		this.codClav = codClav;
	}

	@Column(name = "val_nomb", length = 100)
	public String getValNomb() {
		return this.valNomb;
	}

	public void setValNomb(String valNomb) {
		this.valNomb = valNomb;
	}

	@Column(name = "ind_comp_dato", nullable = false)
	public Integer getIndCompDato() {
		return this.indCompDato;
	}

	public void setIndCompDato(Integer indCompDato) {
		this.indCompDato = indCompDato;
	}

	@Column(name = "cod_clie")
	public Integer getCodClie() {
		return this.codClie;
	}

	public void setCodClie(Integer codClie) {
		this.codClie = codClie;
	}

	@Column(name = "cod_esta_oper")
	public Integer getCodEstaOper() {
		return this.codEstaOper;
	}

	public void setCodEstaOper(Integer codEstaOper) {
		this.codEstaOper = codEstaOper;
	}

	@Column(name = "cod_oper_clie")
	public Integer getCodOperClie() {
		return this.codOperClie;
	}

	public void setCodOperClie(Integer codOperClie) {
		this.codOperClie = codOperClie;
	}

	@Column(name = "cod_perf_usua", nullable = false)
	public Integer getCodPerfUsua() {
		return this.codPerfUsua;
	}

	public void setCodPerfUsua(Integer codPerfUsua) {
		this.codPerfUsua = codPerfUsua;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_ulti_modi_clav", length = 29)
	public Date getFecUltiModiClav() {
		return this.fecUltiModiClav;
	}

	public void setFecUltiModiClav(Date fecUltiModiClav) {
		this.fecUltiModiClav = fecUltiModiClav;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_ulti_acce", length = 29)
	public Date getFecUltiAcce() {
		return this.fecUltiAcce;
	}

	public void setFecUltiAcce(Date fecUltiAcce) {
		this.fecUltiAcce = fecUltiAcce;
	}

	@Column(name = "cod_esta_cuen_usua")
	public Integer getCodEstaCuenUsua() {
		return this.codEstaCuenUsua;
	}

	public void setCodEstaCuenUsua(Integer codEstaCuenUsua) {
		this.codEstaCuenUsua = codEstaCuenUsua;
	}

	@Column(name = "val_toke_cuen", length = 50)
	public String getValTokeCuen() {
		return this.valTokeCuen;
	}

	public void setValTokeCuen(String valTokeCuen) {
		this.valTokeCuen = valTokeCuen;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_toke", length = 29)
	public Date getFecCreaToke() {
		return this.fecCreaToke;
	}

	public void setFecCreaToke(Date fecCreaToke) {
		this.fecCreaToke = fecCreaToke;
	}

	@Column(name = "val_toke_rest_cuen", length = 50)
	public String getValTokeRestCuen() {
		return this.valTokeRestCuen;
	}

	public void setValTokeRestCuen(String valTokeRestCuen) {
		this.valTokeRestCuen = valTokeRestCuen;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_toke_rest_cuen", length = 29)
	public Date getFecCreaTokeRestCuen() {
		return this.fecCreaTokeRestCuen;
	}

	public void setFecCreaTokeRestCuen(Date fecCreaTokeRestCuen) {
		this.fecCreaTokeRestCuen = fecCreaTokeRestCuen;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

	@Column(name = "val_nomb_regi", length = 200)
	public String getValNombRegi() {
		return this.valNombRegi;
	}

	public void setValNombRegi(String valNombRegi) {
		this.valNombRegi = valNombRegi;
	}

	@Column(name = "cod_usua_padr")
	public Integer getCodUsuaPadr() {
		return this.codUsuaPadr;
	}

	public void setCodUsuaPadr(Integer codUsuaPadr) {
		this.codUsuaPadr = codUsuaPadr;
	}

}
