package hibernate.entidades;
// Generated 8 jun. 2022 23:29:22 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TpCupon generated by hbm2java
 */
@Entity
@Table(name = "tp_cupon", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "nom_cupo"))
public class TpCupon implements java.io.Serializable {

	private Integer codCupo;
	private Integer codTipoPersApli;
	private Integer codTipoOperApli;
	private String emaClieCupo;
	private String nomCupo;
	private Date fecInicVige;
	private Date fecFinaVige;
	private Integer canCupo;
	private Double monDescCupo;
	private Integer indReutClie;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpCupon() {
	}

	public TpCupon(Integer codCupo, String nomCupo, Date fecInicVige, Double monDescCupo, Integer indReutClie,
			Integer indEsta, String usuApliCrea, Date fecCreaRegi) {
		this.codCupo = codCupo;
		this.nomCupo = nomCupo;
		this.fecInicVige = fecInicVige;
		this.monDescCupo = monDescCupo;
		this.indReutClie = indReutClie;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpCupon(Integer codCupo, Integer codTipoPersApli, Integer codTipoOperApli, String emaClieCupo,
			String nomCupo, Date fecInicVige, Date fecFinaVige, Integer canCupo, Double monDescCupo,
			Integer indReutClie, Integer indEsta, String usuApliCrea, Date fecCreaRegi, String usuApliModi,
			Date fecModiRegi) {
		this.codCupo = codCupo;
		this.codTipoPersApli = codTipoPersApli;
		this.codTipoOperApli = codTipoOperApli;
		this.emaClieCupo = emaClieCupo;
		this.nomCupo = nomCupo;
		this.fecInicVige = fecInicVige;
		this.fecFinaVige = fecFinaVige;
		this.canCupo = canCupo;
		this.monDescCupo = monDescCupo;
		this.indReutClie = indReutClie;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_cupo", unique = true, nullable = false)
	public Integer getCodCupo() {
		return this.codCupo;
	}

	public void setCodCupo(Integer codCupo) {
		this.codCupo = codCupo;
	}

	@Column(name = "cod_tipo_pers_apli")
	public Integer getCodTipoPersApli() {
		return this.codTipoPersApli;
	}

	public void setCodTipoPersApli(Integer codTipoPersApli) {
		this.codTipoPersApli = codTipoPersApli;
	}

	@Column(name = "cod_tipo_oper_apli")
	public Integer getCodTipoOperApli() {
		return this.codTipoOperApli;
	}

	public void setCodTipoOperApli(Integer codTipoOperApli) {
		this.codTipoOperApli = codTipoOperApli;
	}

	@Column(name = "ema_clie_cupo", length = 200)
	public String getEmaClieCupo() {
		return this.emaClieCupo;
	}

	public void setEmaClieCupo(String emaClieCupo) {
		this.emaClieCupo = emaClieCupo;
	}

	@Column(name = "nom_cupo", unique = true, nullable = false, length = 50)
	public String getNomCupo() {
		return this.nomCupo;
	}

	public void setNomCupo(String nomCupo) {
		this.nomCupo = nomCupo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_inic_vige", nullable = false, length = 29)
	public Date getFecInicVige() {
		return this.fecInicVige;
	}

	public void setFecInicVige(Date fecInicVige) {
		this.fecInicVige = fecInicVige;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_fina_vige", length = 29)
	public Date getFecFinaVige() {
		return this.fecFinaVige;
	}

	public void setFecFinaVige(Date fecFinaVige) {
		this.fecFinaVige = fecFinaVige;
	}

	@Column(name = "can_cupo")
	public Integer getCanCupo() {
		return this.canCupo;
	}

	public void setCanCupo(Integer canCupo) {
		this.canCupo = canCupo;
	}

	@Column(name = "mon_desc_cupo", nullable = false, precision = 17, scale = 17)
	public Double getMonDescCupo() {
		return this.monDescCupo;
	}

	public void setMonDescCupo(Double monDescCupo) {
		this.monDescCupo = monDescCupo;
	}

	@Column(name = "ind_reut_clie", nullable = false)
	public Integer getIndReutClie() {
		return this.indReutClie;
	}

	public void setIndReutClie(Integer indReutClie) {
		this.indReutClie = indReutClie;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
