package hibernate.entidades;
// Generated 17 ago. 2022 04:52:55 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpFactuDocumCabec generated by hbm2java
 */
@Entity
@Table(name = "tp_factu_docum_cabec", schema = "public")
public class TpFactuDocumCabec implements java.io.Serializable {

	private Integer codFactDocuCabec;
	private Integer codOperClie;
	private short tipoDeComprobante;
	private String serie;
	private Integer numero;
	private short sunatTransaction;
	private String clienteTipoDeDocumento;
	private String clienteNumeroDeDocumento;
	private String clienteDenominacion;
	private String clienteDireccion;
	private String clienteEmail;
	private String clienteEmail1;
	private String clienteEmail2;
	private Date fechaDeEmision;
	private Date fechaDeVencimiento;
	private short moneda;
	private Double tipoDeCambio;
	private Double porcentajeDeIgv;
	private Double descuentoGlobal;
	private Double totalDescuento;
	private Double totalAnticipo;
	private Double totalGravada;
	private Double totalInafecta;
	private Double totalExonerada;
	private Double totalIgv;
	private Double totalGratuita;
	private Double totalOtrosCargos;
	private Double totalIsc;
	private Double total;
	private Short percepcionTipo;
	private Double percepcionBaseImponible;
	private Double totalPercepcion;
	private Double totalIncluidoPercepcion;
	private Short detraccion;
	private String observaciones;
	private Short documentoQueSeModificaTipo;
	private String documentoQueSeModificaSerie;
	private Integer documentoQueSeModificaNumero;
	private Short tipoDeNotaDeCredito;
	private Short tipoDeNotaDeDebito;
	private Short enviarAutomaticamenteALaSunat;
	private Short enviarAutomaticamenteAlCliente;
	private String codigoUnico;
	private String condicionesDePago;
	private String medioDePago;
	private String placaVehiculo;
	private String ordenCompraServicio;
	private String formatoDePdf;
	private String repuestaEnlace;
	private Short repuestaAceptadaPorSunat;
	private String repuestaSunatDescription;
	private String repuestaSunatNote;
	private String repuestaSunatResponsecode;
	private String repuestaSunatSoapError;
	private Short repuestaAnulado;
	private String repuestaPdfZipBase64;
	private String repuestaXmlZipBase64;
	private String repuestaCdrZipBase64;
	private String repuestaCadenaParaCodigoQr;
	private String repuestaCodigoHash;
	private String repuestaEnlaceDelPdf;
	private String repuestaEnlaceDelXml;
	private String repuestaEnlaceDelCdr;
	private String repuestaErrors;
	private String repuestaCodigoError;
	private String desCortDocuGene;
	private Short codEstaDocu;
	private String menDetaDocu;
	private short indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpFactuDocumCabec() {
	}

	public TpFactuDocumCabec(Integer codFactDocuCabec, short tipoDeComprobante, String serie, Integer numero,
			short sunatTransaction, String clienteTipoDeDocumento, String clienteNumeroDeDocumento,
			String clienteDenominacion, String clienteDireccion, Date fechaDeEmision, short moneda, Double total,
			String desCortDocuGene, short indEsta, String usuApliCrea, Date fecCreaRegi) {
		this.codFactDocuCabec = codFactDocuCabec;
		this.tipoDeComprobante = tipoDeComprobante;
		this.serie = serie;
		this.numero = numero;
		this.sunatTransaction = sunatTransaction;
		this.clienteTipoDeDocumento = clienteTipoDeDocumento;
		this.clienteNumeroDeDocumento = clienteNumeroDeDocumento;
		this.clienteDenominacion = clienteDenominacion;
		this.clienteDireccion = clienteDireccion;
		this.fechaDeEmision = fechaDeEmision;
		this.moneda = moneda;
		this.total = total;
		this.desCortDocuGene = desCortDocuGene;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpFactuDocumCabec(Integer codFactDocuCabec, Integer codOperClie, short tipoDeComprobante, String serie,
			Integer numero, short sunatTransaction, String clienteTipoDeDocumento, String clienteNumeroDeDocumento,
			String clienteDenominacion, String clienteDireccion, String clienteEmail, String clienteEmail1,
			String clienteEmail2, Date fechaDeEmision, Date fechaDeVencimiento, short moneda, Double tipoDeCambio,
			Double porcentajeDeIgv, Double descuentoGlobal, Double totalDescuento, Double totalAnticipo,
			Double totalGravada, Double totalInafecta, Double totalExonerada, Double totalIgv, Double totalGratuita,
			Double totalOtrosCargos, Double totalIsc, Double total, Short percepcionTipo,
			Double percepcionBaseImponible, Double totalPercepcion, Double totalIncluidoPercepcion, Short detraccion,
			String observaciones, Short documentoQueSeModificaTipo, String documentoQueSeModificaSerie,
			Integer documentoQueSeModificaNumero, Short tipoDeNotaDeCredito, Short tipoDeNotaDeDebito,
			Short enviarAutomaticamenteALaSunat, Short enviarAutomaticamenteAlCliente, String codigoUnico,
			String condicionesDePago, String medioDePago, String placaVehiculo, String ordenCompraServicio,
			String formatoDePdf, String repuestaEnlace, Short repuestaAceptadaPorSunat, String repuestaSunatDescription,
			String repuestaSunatNote, String repuestaSunatResponsecode, String repuestaSunatSoapError,
			Short repuestaAnulado, String repuestaPdfZipBase64, String repuestaXmlZipBase64,
			String repuestaCdrZipBase64, String repuestaCadenaParaCodigoQr, String repuestaCodigoHash,
			String repuestaEnlaceDelPdf, String repuestaEnlaceDelXml, String repuestaEnlaceDelCdr,
			String repuestaErrors, String repuestaCodigoError, String desCortDocuGene, Short codEstaDocu,
			String menDetaDocu, short indEsta, String usuApliCrea, Date fecCreaRegi, String usuApliModi,
			Date fecModiRegi) {
		this.codFactDocuCabec = codFactDocuCabec;
		this.codOperClie = codOperClie;
		this.tipoDeComprobante = tipoDeComprobante;
		this.serie = serie;
		this.numero = numero;
		this.sunatTransaction = sunatTransaction;
		this.clienteTipoDeDocumento = clienteTipoDeDocumento;
		this.clienteNumeroDeDocumento = clienteNumeroDeDocumento;
		this.clienteDenominacion = clienteDenominacion;
		this.clienteDireccion = clienteDireccion;
		this.clienteEmail = clienteEmail;
		this.clienteEmail1 = clienteEmail1;
		this.clienteEmail2 = clienteEmail2;
		this.fechaDeEmision = fechaDeEmision;
		this.fechaDeVencimiento = fechaDeVencimiento;
		this.moneda = moneda;
		this.tipoDeCambio = tipoDeCambio;
		this.porcentajeDeIgv = porcentajeDeIgv;
		this.descuentoGlobal = descuentoGlobal;
		this.totalDescuento = totalDescuento;
		this.totalAnticipo = totalAnticipo;
		this.totalGravada = totalGravada;
		this.totalInafecta = totalInafecta;
		this.totalExonerada = totalExonerada;
		this.totalIgv = totalIgv;
		this.totalGratuita = totalGratuita;
		this.totalOtrosCargos = totalOtrosCargos;
		this.totalIsc = totalIsc;
		this.total = total;
		this.percepcionTipo = percepcionTipo;
		this.percepcionBaseImponible = percepcionBaseImponible;
		this.totalPercepcion = totalPercepcion;
		this.totalIncluidoPercepcion = totalIncluidoPercepcion;
		this.detraccion = detraccion;
		this.observaciones = observaciones;
		this.documentoQueSeModificaTipo = documentoQueSeModificaTipo;
		this.documentoQueSeModificaSerie = documentoQueSeModificaSerie;
		this.documentoQueSeModificaNumero = documentoQueSeModificaNumero;
		this.tipoDeNotaDeCredito = tipoDeNotaDeCredito;
		this.tipoDeNotaDeDebito = tipoDeNotaDeDebito;
		this.enviarAutomaticamenteALaSunat = enviarAutomaticamenteALaSunat;
		this.enviarAutomaticamenteAlCliente = enviarAutomaticamenteAlCliente;
		this.codigoUnico = codigoUnico;
		this.condicionesDePago = condicionesDePago;
		this.medioDePago = medioDePago;
		this.placaVehiculo = placaVehiculo;
		this.ordenCompraServicio = ordenCompraServicio;
		this.formatoDePdf = formatoDePdf;
		this.repuestaEnlace = repuestaEnlace;
		this.repuestaAceptadaPorSunat = repuestaAceptadaPorSunat;
		this.repuestaSunatDescription = repuestaSunatDescription;
		this.repuestaSunatNote = repuestaSunatNote;
		this.repuestaSunatResponsecode = repuestaSunatResponsecode;
		this.repuestaSunatSoapError = repuestaSunatSoapError;
		this.repuestaAnulado = repuestaAnulado;
		this.repuestaPdfZipBase64 = repuestaPdfZipBase64;
		this.repuestaXmlZipBase64 = repuestaXmlZipBase64;
		this.repuestaCdrZipBase64 = repuestaCdrZipBase64;
		this.repuestaCadenaParaCodigoQr = repuestaCadenaParaCodigoQr;
		this.repuestaCodigoHash = repuestaCodigoHash;
		this.repuestaEnlaceDelPdf = repuestaEnlaceDelPdf;
		this.repuestaEnlaceDelXml = repuestaEnlaceDelXml;
		this.repuestaEnlaceDelCdr = repuestaEnlaceDelCdr;
		this.repuestaErrors = repuestaErrors;
		this.repuestaCodigoError = repuestaCodigoError;
		this.desCortDocuGene = desCortDocuGene;
		this.codEstaDocu = codEstaDocu;
		this.menDetaDocu = menDetaDocu;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_fact_docu_cabec", unique = true, nullable = false)
	public Integer getCodFactDocuCabec() {
		return this.codFactDocuCabec;
	}

	public void setCodFactDocuCabec(Integer codFactDocuCabec) {
		this.codFactDocuCabec = codFactDocuCabec;
	}

	@Column(name = "cod_oper_clie")
	public Integer getCodOperClie() {
		return this.codOperClie;
	}

	public void setCodOperClie(Integer codOperClie) {
		this.codOperClie = codOperClie;
	}

	@Column(name = "tipo_de_comprobante", nullable = false)
	public short getTipoDeComprobante() {
		return this.tipoDeComprobante;
	}

	public void setTipoDeComprobante(short tipoDeComprobante) {
		this.tipoDeComprobante = tipoDeComprobante;
	}

	@Column(name = "serie", nullable = false, length = 4)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@Column(name = "numero", nullable = false)
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "sunat_transaction", nullable = false)
	public short getSunatTransaction() {
		return this.sunatTransaction;
	}

	public void setSunatTransaction(short sunatTransaction) {
		this.sunatTransaction = sunatTransaction;
	}

	@Column(name = "cliente_tipo_de_documento", nullable = false, length = 1)
	public String getClienteTipoDeDocumento() {
		return this.clienteTipoDeDocumento;
	}

	public void setClienteTipoDeDocumento(String clienteTipoDeDocumento) {
		this.clienteTipoDeDocumento = clienteTipoDeDocumento;
	}

	@Column(name = "cliente_numero_de_documento", nullable = false, length = 15)
	public String getClienteNumeroDeDocumento() {
		return this.clienteNumeroDeDocumento;
	}

	public void setClienteNumeroDeDocumento(String clienteNumeroDeDocumento) {
		this.clienteNumeroDeDocumento = clienteNumeroDeDocumento;
	}

	@Column(name = "cliente_denominacion", nullable = false, length = 100)
	public String getClienteDenominacion() {
		return this.clienteDenominacion;
	}

	public void setClienteDenominacion(String clienteDenominacion) {
		this.clienteDenominacion = clienteDenominacion;
	}

	@Column(name = "cliente_direccion", nullable = false, length = 100)
	public String getClienteDireccion() {
		return this.clienteDireccion;
	}

	public void setClienteDireccion(String clienteDireccion) {
		this.clienteDireccion = clienteDireccion;
	}

	@Column(name = "cliente_email", length = 250)
	public String getClienteEmail() {
		return this.clienteEmail;
	}

	public void setClienteEmail(String clienteEmail) {
		this.clienteEmail = clienteEmail;
	}

	@Column(name = "cliente_email_1", length = 250)
	public String getClienteEmail1() {
		return this.clienteEmail1;
	}

	public void setClienteEmail1(String clienteEmail1) {
		this.clienteEmail1 = clienteEmail1;
	}

	@Column(name = "cliente_email_2", length = 250)
	public String getClienteEmail2() {
		return this.clienteEmail2;
	}

	public void setClienteEmail2(String clienteEmail2) {
		this.clienteEmail2 = clienteEmail2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_de_emision", nullable = false, length = 29)
	public Date getFechaDeEmision() {
		return this.fechaDeEmision;
	}

	public void setFechaDeEmision(Date fechaDeEmision) {
		this.fechaDeEmision = fechaDeEmision;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_de_vencimiento", length = 29)
	public Date getFechaDeVencimiento() {
		return this.fechaDeVencimiento;
	}

	public void setFechaDeVencimiento(Date fechaDeVencimiento) {
		this.fechaDeVencimiento = fechaDeVencimiento;
	}

	@Column(name = "moneda", nullable = false)
	public short getMoneda() {
		return this.moneda;
	}

	public void setMoneda(short moneda) {
		this.moneda = moneda;
	}

	@Column(name = "tipo_de_cambio", precision = 17, scale = 17)
	public Double getTipoDeCambio() {
		return this.tipoDeCambio;
	}

	public void setTipoDeCambio(Double tipoDeCambio) {
		this.tipoDeCambio = tipoDeCambio;
	}

	@Column(name = "porcentaje_de_igv", precision = 17, scale = 17)
	public Double getPorcentajeDeIgv() {
		return this.porcentajeDeIgv;
	}

	public void setPorcentajeDeIgv(Double porcentajeDeIgv) {
		this.porcentajeDeIgv = porcentajeDeIgv;
	}

	@Column(name = "descuento_global", precision = 17, scale = 17)
	public Double getDescuentoGlobal() {
		return this.descuentoGlobal;
	}

	public void setDescuentoGlobal(Double descuentoGlobal) {
		this.descuentoGlobal = descuentoGlobal;
	}

	@Column(name = "total_descuento", precision = 17, scale = 17)
	public Double getTotalDescuento() {
		return this.totalDescuento;
	}

	public void setTotalDescuento(Double totalDescuento) {
		this.totalDescuento = totalDescuento;
	}

	@Column(name = "total_anticipo", precision = 17, scale = 17)
	public Double getTotalAnticipo() {
		return this.totalAnticipo;
	}

	public void setTotalAnticipo(Double totalAnticipo) {
		this.totalAnticipo = totalAnticipo;
	}

	@Column(name = "total_gravada", precision = 17, scale = 17)
	public Double getTotalGravada() {
		return this.totalGravada;
	}

	public void setTotalGravada(Double totalGravada) {
		this.totalGravada = totalGravada;
	}

	@Column(name = "total_inafecta", precision = 17, scale = 17)
	public Double getTotalInafecta() {
		return this.totalInafecta;
	}

	public void setTotalInafecta(Double totalInafecta) {
		this.totalInafecta = totalInafecta;
	}

	@Column(name = "total_exonerada", precision = 17, scale = 17)
	public Double getTotalExonerada() {
		return this.totalExonerada;
	}

	public void setTotalExonerada(Double totalExonerada) {
		this.totalExonerada = totalExonerada;
	}

	@Column(name = "total_igv", precision = 17, scale = 17)
	public Double getTotalIgv() {
		return this.totalIgv;
	}

	public void setTotalIgv(Double totalIgv) {
		this.totalIgv = totalIgv;
	}

	@Column(name = "total_gratuita", precision = 17, scale = 17)
	public Double getTotalGratuita() {
		return this.totalGratuita;
	}

	public void setTotalGratuita(Double totalGratuita) {
		this.totalGratuita = totalGratuita;
	}

	@Column(name = "total_otros_cargos", precision = 17, scale = 17)
	public Double getTotalOtrosCargos() {
		return this.totalOtrosCargos;
	}

	public void setTotalOtrosCargos(Double totalOtrosCargos) {
		this.totalOtrosCargos = totalOtrosCargos;
	}

	@Column(name = "total_isc", precision = 17, scale = 17)
	public Double getTotalIsc() {
		return this.totalIsc;
	}

	public void setTotalIsc(Double totalIsc) {
		this.totalIsc = totalIsc;
	}

	@Column(name = "total", nullable = false, precision = 17, scale = 17)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	@Column(name = "percepcion_tipo")
	public Short getPercepcionTipo() {
		return this.percepcionTipo;
	}

	public void setPercepcionTipo(Short percepcionTipo) {
		this.percepcionTipo = percepcionTipo;
	}

	@Column(name = "percepcion_base_imponible", precision = 17, scale = 17)
	public Double getPercepcionBaseImponible() {
		return this.percepcionBaseImponible;
	}

	public void setPercepcionBaseImponible(Double percepcionBaseImponible) {
		this.percepcionBaseImponible = percepcionBaseImponible;
	}

	@Column(name = "total_percepcion", precision = 17, scale = 17)
	public Double getTotalPercepcion() {
		return this.totalPercepcion;
	}

	public void setTotalPercepcion(Double totalPercepcion) {
		this.totalPercepcion = totalPercepcion;
	}

	@Column(name = "total_incluido_percepcion", precision = 17, scale = 17)
	public Double getTotalIncluidoPercepcion() {
		return this.totalIncluidoPercepcion;
	}

	public void setTotalIncluidoPercepcion(Double totalIncluidoPercepcion) {
		this.totalIncluidoPercepcion = totalIncluidoPercepcion;
	}

	@Column(name = "detraccion")
	public Short getDetraccion() {
		return this.detraccion;
	}

	public void setDetraccion(Short detraccion) {
		this.detraccion = detraccion;
	}

	@Column(name = "observaciones", length = 1000)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "documento_que_se_modifica_tipo")
	public Short getDocumentoQueSeModificaTipo() {
		return this.documentoQueSeModificaTipo;
	}

	public void setDocumentoQueSeModificaTipo(Short documentoQueSeModificaTipo) {
		this.documentoQueSeModificaTipo = documentoQueSeModificaTipo;
	}

	@Column(name = "documento_que_se_modifica_serie", length = 4)
	public String getDocumentoQueSeModificaSerie() {
		return this.documentoQueSeModificaSerie;
	}

	public void setDocumentoQueSeModificaSerie(String documentoQueSeModificaSerie) {
		this.documentoQueSeModificaSerie = documentoQueSeModificaSerie;
	}

	@Column(name = "documento_que_se_modifica_numero")
	public Integer getDocumentoQueSeModificaNumero() {
		return this.documentoQueSeModificaNumero;
	}

	public void setDocumentoQueSeModificaNumero(Integer documentoQueSeModificaNumero) {
		this.documentoQueSeModificaNumero = documentoQueSeModificaNumero;
	}

	@Column(name = "tipo_de_nota_de_credito")
	public Short getTipoDeNotaDeCredito() {
		return this.tipoDeNotaDeCredito;
	}

	public void setTipoDeNotaDeCredito(Short tipoDeNotaDeCredito) {
		this.tipoDeNotaDeCredito = tipoDeNotaDeCredito;
	}

	@Column(name = "tipo_de_nota_de_debito")
	public Short getTipoDeNotaDeDebito() {
		return this.tipoDeNotaDeDebito;
	}

	public void setTipoDeNotaDeDebito(Short tipoDeNotaDeDebito) {
		this.tipoDeNotaDeDebito = tipoDeNotaDeDebito;
	}

	@Column(name = "enviar_automaticamente_a_la_sunat")
	public Short getEnviarAutomaticamenteALaSunat() {
		return this.enviarAutomaticamenteALaSunat;
	}

	public void setEnviarAutomaticamenteALaSunat(Short enviarAutomaticamenteALaSunat) {
		this.enviarAutomaticamenteALaSunat = enviarAutomaticamenteALaSunat;
	}

	@Column(name = "enviar_automaticamente_al_cliente")
	public Short getEnviarAutomaticamenteAlCliente() {
		return this.enviarAutomaticamenteAlCliente;
	}

	public void setEnviarAutomaticamenteAlCliente(Short enviarAutomaticamenteAlCliente) {
		this.enviarAutomaticamenteAlCliente = enviarAutomaticamenteAlCliente;
	}

	@Column(name = "codigo_unico", length = 20)
	public String getCodigoUnico() {
		return this.codigoUnico;
	}

	public void setCodigoUnico(String codigoUnico) {
		this.codigoUnico = codigoUnico;
	}

	@Column(name = "condiciones_de_pago", length = 250)
	public String getCondicionesDePago() {
		return this.condicionesDePago;
	}

	public void setCondicionesDePago(String condicionesDePago) {
		this.condicionesDePago = condicionesDePago;
	}

	@Column(name = "medio_de_pago", length = 250)
	public String getMedioDePago() {
		return this.medioDePago;
	}

	public void setMedioDePago(String medioDePago) {
		this.medioDePago = medioDePago;
	}

	@Column(name = "placa_vehiculo", length = 8)
	public String getPlacaVehiculo() {
		return this.placaVehiculo;
	}

	public void setPlacaVehiculo(String placaVehiculo) {
		this.placaVehiculo = placaVehiculo;
	}

	@Column(name = "orden_compra_servicio", length = 20)
	public String getOrdenCompraServicio() {
		return this.ordenCompraServicio;
	}

	public void setOrdenCompraServicio(String ordenCompraServicio) {
		this.ordenCompraServicio = ordenCompraServicio;
	}

	@Column(name = "formato_de_pdf", length = 6)
	public String getFormatoDePdf() {
		return this.formatoDePdf;
	}

	public void setFormatoDePdf(String formatoDePdf) {
		this.formatoDePdf = formatoDePdf;
	}

	@Column(name = "repuesta_enlace", length = 250)
	public String getRepuestaEnlace() {
		return this.repuestaEnlace;
	}

	public void setRepuestaEnlace(String repuestaEnlace) {
		this.repuestaEnlace = repuestaEnlace;
	}

	@Column(name = "repuesta_aceptada_por_sunat")
	public Short getRepuestaAceptadaPorSunat() {
		return this.repuestaAceptadaPorSunat;
	}

	public void setRepuestaAceptadaPorSunat(Short repuestaAceptadaPorSunat) {
		this.repuestaAceptadaPorSunat = repuestaAceptadaPorSunat;
	}

	@Column(name = "repuesta_sunat_description", length = 1000)
	public String getRepuestaSunatDescription() {
		return this.repuestaSunatDescription;
	}

	public void setRepuestaSunatDescription(String repuestaSunatDescription) {
		this.repuestaSunatDescription = repuestaSunatDescription;
	}

	@Column(name = "repuesta_sunat_note", length = 1000)
	public String getRepuestaSunatNote() {
		return this.repuestaSunatNote;
	}

	public void setRepuestaSunatNote(String repuestaSunatNote) {
		this.repuestaSunatNote = repuestaSunatNote;
	}

	@Column(name = "repuesta_sunat_responsecode", length = 1000)
	public String getRepuestaSunatResponsecode() {
		return this.repuestaSunatResponsecode;
	}

	public void setRepuestaSunatResponsecode(String repuestaSunatResponsecode) {
		this.repuestaSunatResponsecode = repuestaSunatResponsecode;
	}

	@Column(name = "repuesta_sunat_soap_error", length = 1000)
	public String getRepuestaSunatSoapError() {
		return this.repuestaSunatSoapError;
	}

	public void setRepuestaSunatSoapError(String repuestaSunatSoapError) {
		this.repuestaSunatSoapError = repuestaSunatSoapError;
	}

	@Column(name = "repuesta_anulado")
	public Short getRepuestaAnulado() {
		return this.repuestaAnulado;
	}

	public void setRepuestaAnulado(Short repuestaAnulado) {
		this.repuestaAnulado = repuestaAnulado;
	}

	@Column(name = "repuesta_pdf_zip_base64", length = 1000)
	public String getRepuestaPdfZipBase64() {
		return this.repuestaPdfZipBase64;
	}

	public void setRepuestaPdfZipBase64(String repuestaPdfZipBase64) {
		this.repuestaPdfZipBase64 = repuestaPdfZipBase64;
	}

	@Column(name = "repuesta_xml_zip_base64", length = 1000)
	public String getRepuestaXmlZipBase64() {
		return this.repuestaXmlZipBase64;
	}

	public void setRepuestaXmlZipBase64(String repuestaXmlZipBase64) {
		this.repuestaXmlZipBase64 = repuestaXmlZipBase64;
	}

	@Column(name = "repuesta_cdr_zip_base64", length = 1000)
	public String getRepuestaCdrZipBase64() {
		return this.repuestaCdrZipBase64;
	}

	public void setRepuestaCdrZipBase64(String repuestaCdrZipBase64) {
		this.repuestaCdrZipBase64 = repuestaCdrZipBase64;
	}

	@Column(name = "repuesta_cadena_para_codigo_qr", length = 250)
	public String getRepuestaCadenaParaCodigoQr() {
		return this.repuestaCadenaParaCodigoQr;
	}

	public void setRepuestaCadenaParaCodigoQr(String repuestaCadenaParaCodigoQr) {
		this.repuestaCadenaParaCodigoQr = repuestaCadenaParaCodigoQr;
	}

	@Column(name = "repuesta_codigo_hash", length = 250)
	public String getRepuestaCodigoHash() {
		return this.repuestaCodigoHash;
	}

	public void setRepuestaCodigoHash(String repuestaCodigoHash) {
		this.repuestaCodigoHash = repuestaCodigoHash;
	}

	@Column(name = "repuesta_enlace_del_pdf", length = 300)
	public String getRepuestaEnlaceDelPdf() {
		return this.repuestaEnlaceDelPdf;
	}

	public void setRepuestaEnlaceDelPdf(String repuestaEnlaceDelPdf) {
		this.repuestaEnlaceDelPdf = repuestaEnlaceDelPdf;
	}

	@Column(name = "repuesta_enlace_del_xml", length = 300)
	public String getRepuestaEnlaceDelXml() {
		return this.repuestaEnlaceDelXml;
	}

	public void setRepuestaEnlaceDelXml(String repuestaEnlaceDelXml) {
		this.repuestaEnlaceDelXml = repuestaEnlaceDelXml;
	}

	@Column(name = "repuesta_enlace_del_cdr", length = 300)
	public String getRepuestaEnlaceDelCdr() {
		return this.repuestaEnlaceDelCdr;
	}

	public void setRepuestaEnlaceDelCdr(String repuestaEnlaceDelCdr) {
		this.repuestaEnlaceDelCdr = repuestaEnlaceDelCdr;
	}

	@Column(name = "repuesta_errors", length = 250)
	public String getRepuestaErrors() {
		return this.repuestaErrors;
	}

	public void setRepuestaErrors(String repuestaErrors) {
		this.repuestaErrors = repuestaErrors;
	}

	@Column(name = "repuesta_codigo_error", length = 3)
	public String getRepuestaCodigoError() {
		return this.repuestaCodigoError;
	}

	public void setRepuestaCodigoError(String repuestaCodigoError) {
		this.repuestaCodigoError = repuestaCodigoError;
	}

	@Column(name = "des_cort_docu_gene", nullable = false, length = 8)
	public String getDesCortDocuGene() {
		return this.desCortDocuGene;
	}

	public void setDesCortDocuGene(String desCortDocuGene) {
		this.desCortDocuGene = desCortDocuGene;
	}

	@Column(name = "cod_esta_docu")
	public Short getCodEstaDocu() {
		return this.codEstaDocu;
	}

	public void setCodEstaDocu(Short codEstaDocu) {
		this.codEstaDocu = codEstaDocu;
	}

	@Column(name = "men_deta_docu", length = 250)
	public String getMenDetaDocu() {
		return this.menDetaDocu;
	}

	public void setMenDetaDocu(String menDetaDocu) {
		this.menDetaDocu = menDetaDocu;
	}

	@Column(name = "ind_esta", nullable = false)
	public short getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(short indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
