package hibernate.entidades;
// Generated 12/09/2019 12:32:03 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpFactDocumDetal generated by hbm2java
 */
@Entity
@Table(name = "tp_fact_docum_detal", schema = "public")
public class TpFactDocumDetal implements java.io.Serializable {

	private Integer codFactDocuDetal;
	private TpFactDocumCabec tpFactDocumCabec;
	private String codUnidMediItem;
	private String canUnidItem;
	private String codProd;
	private String codProdSuna;
	private String desDetaServBien;
	private String valUnit;
	private String triSumaTribItem;
	private String triCodiTipoProdIgv;
	private String triMontIgvItem;
	private String triBaseImpoIgvItem;
	private String triNombTribItem;
	private String triCodiTipoProdItem;
	private String triAfecIgvItem;
	private String triPorcIgv;
	private String triIscCodiTipoProdIsc;
	private String triIscMontIscItem;
	private String triIscBaseImpoIscItem;
	private String triIscNombTribItem;
	private String triIscCodiTipoTribItem;
	private String triIscTipoSistIsc;
	private String triIscPorcIsc;
	private String triOtroCodiTipoTribOtro;
	private String triOtroMontTribItem;
	private String triOtroBaseImpoTribItem;
	private String triOtroNombTribItem;
	private String triOtroCodiTribItem;
	private String triOtroPorcTribItem;
	private String preVentUnit;
	private String valVentItem;
	private String valRefeUnitGrat;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpFactDocumDetal() {
		tpFactDocumCabec = new TpFactDocumCabec();
	}

	public TpFactDocumDetal(Integer codFactDocuDetal, TpFactDocumCabec tpFactDocumCabec, String codUnidMediItem,
			String canUnidItem, String desDetaServBien, String valUnit, String triSumaTribItem,
			String triCodiTipoProdIgv, String triMontIgvItem, String triBaseImpoIgvItem, String triNombTribItem,
			String triCodiTipoProdItem, String triAfecIgvItem, String triPorcIgv, String triIscCodiTipoProdIsc,
			String triIscMontIscItem, String triIscBaseImpoIscItem, String triIscNombTribItem,
			String triIscCodiTipoTribItem, String triIscPorcIsc, String triOtroCodiTipoTribOtro,
			String triOtroMontTribItem, String triOtroBaseImpoTribItem, String triOtroNombTribItem,
			String triOtroCodiTribItem, String triOtroPorcTribItem, String preVentUnit, String valVentItem,
			Integer indEsta, String usuApliCrea, Date fecCreaRegi) {
		this.codFactDocuDetal = codFactDocuDetal;
		this.tpFactDocumCabec = tpFactDocumCabec;
		this.codUnidMediItem = codUnidMediItem;
		this.canUnidItem = canUnidItem;
		this.desDetaServBien = desDetaServBien;
		this.valUnit = valUnit;
		this.triSumaTribItem = triSumaTribItem;
		this.triCodiTipoProdIgv = triCodiTipoProdIgv;
		this.triMontIgvItem = triMontIgvItem;
		this.triBaseImpoIgvItem = triBaseImpoIgvItem;
		this.triNombTribItem = triNombTribItem;
		this.triCodiTipoProdItem = triCodiTipoProdItem;
		this.triAfecIgvItem = triAfecIgvItem;
		this.triPorcIgv = triPorcIgv;
		this.triIscCodiTipoProdIsc = triIscCodiTipoProdIsc;
		this.triIscMontIscItem = triIscMontIscItem;
		this.triIscBaseImpoIscItem = triIscBaseImpoIscItem;
		this.triIscNombTribItem = triIscNombTribItem;
		this.triIscCodiTipoTribItem = triIscCodiTipoTribItem;
		this.triIscPorcIsc = triIscPorcIsc;
		this.triOtroCodiTipoTribOtro = triOtroCodiTipoTribOtro;
		this.triOtroMontTribItem = triOtroMontTribItem;
		this.triOtroBaseImpoTribItem = triOtroBaseImpoTribItem;
		this.triOtroNombTribItem = triOtroNombTribItem;
		this.triOtroCodiTribItem = triOtroCodiTribItem;
		this.triOtroPorcTribItem = triOtroPorcTribItem;
		this.preVentUnit = preVentUnit;
		this.valVentItem = valVentItem;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpFactDocumDetal(Integer codFactDocuDetal, TpFactDocumCabec tpFactDocumCabec, String codUnidMediItem,
			String canUnidItem, String codProd, String codProdSuna, String desDetaServBien, String valUnit,
			String triSumaTribItem, String triCodiTipoProdIgv, String triMontIgvItem, String triBaseImpoIgvItem,
			String triNombTribItem, String triCodiTipoProdItem, String triAfecIgvItem, String triPorcIgv,
			String triIscCodiTipoProdIsc, String triIscMontIscItem, String triIscBaseImpoIscItem,
			String triIscNombTribItem, String triIscCodiTipoTribItem, String triIscTipoSistIsc, String triIscPorcIsc,
			String triOtroCodiTipoTribOtro, String triOtroMontTribItem, String triOtroBaseImpoTribItem,
			String triOtroNombTribItem, String triOtroCodiTribItem, String triOtroPorcTribItem, String preVentUnit,
			String valVentItem, String valRefeUnitGrat, Integer indEsta, String usuApliCrea, Date fecCreaRegi,
			String usuApliModi, Date fecModiRegi) {
		this.codFactDocuDetal = codFactDocuDetal;
		this.tpFactDocumCabec = tpFactDocumCabec;
		this.codUnidMediItem = codUnidMediItem;
		this.canUnidItem = canUnidItem;
		this.codProd = codProd;
		this.codProdSuna = codProdSuna;
		this.desDetaServBien = desDetaServBien;
		this.valUnit = valUnit;
		this.triSumaTribItem = triSumaTribItem;
		this.triCodiTipoProdIgv = triCodiTipoProdIgv;
		this.triMontIgvItem = triMontIgvItem;
		this.triBaseImpoIgvItem = triBaseImpoIgvItem;
		this.triNombTribItem = triNombTribItem;
		this.triCodiTipoProdItem = triCodiTipoProdItem;
		this.triAfecIgvItem = triAfecIgvItem;
		this.triPorcIgv = triPorcIgv;
		this.triIscCodiTipoProdIsc = triIscCodiTipoProdIsc;
		this.triIscMontIscItem = triIscMontIscItem;
		this.triIscBaseImpoIscItem = triIscBaseImpoIscItem;
		this.triIscNombTribItem = triIscNombTribItem;
		this.triIscCodiTipoTribItem = triIscCodiTipoTribItem;
		this.triIscTipoSistIsc = triIscTipoSistIsc;
		this.triIscPorcIsc = triIscPorcIsc;
		this.triOtroCodiTipoTribOtro = triOtroCodiTipoTribOtro;
		this.triOtroMontTribItem = triOtroMontTribItem;
		this.triOtroBaseImpoTribItem = triOtroBaseImpoTribItem;
		this.triOtroNombTribItem = triOtroNombTribItem;
		this.triOtroCodiTribItem = triOtroCodiTribItem;
		this.triOtroPorcTribItem = triOtroPorcTribItem;
		this.preVentUnit = preVentUnit;
		this.valVentItem = valVentItem;
		this.valRefeUnitGrat = valRefeUnitGrat;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_fact_docu_detal", unique = true, nullable = false)
	public Integer getCodFactDocuDetal() {
		return this.codFactDocuDetal;
	}

	public void setCodFactDocuDetal(Integer codFactDocuDetal) {
		this.codFactDocuDetal = codFactDocuDetal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_fact_docu_cabec", nullable = false)
	public TpFactDocumCabec getTpFactDocumCabec() {
		return this.tpFactDocumCabec;
	}

	public void setTpFactDocumCabec(TpFactDocumCabec tpFactDocumCabec) {
		this.tpFactDocumCabec = tpFactDocumCabec;
	}

	@Column(name = "cod_unid_medi_item", nullable = false, length = 3)
	public String getCodUnidMediItem() {
		return this.codUnidMediItem;
	}

	public void setCodUnidMediItem(String codUnidMediItem) {
		this.codUnidMediItem = codUnidMediItem;
	}

	@Column(name = "can_unid_item", nullable = false, length = 23)
	public String getCanUnidItem() {
		return this.canUnidItem;
	}

	public void setCanUnidItem(String canUnidItem) {
		this.canUnidItem = canUnidItem;
	}

	@Column(name = "cod_prod", length = 30)
	public String getCodProd() {
		return this.codProd;
	}

	public void setCodProd(String codProd) {
		this.codProd = codProd;
	}

	@Column(name = "cod_prod_suna", length = 8)
	public String getCodProdSuna() {
		return this.codProdSuna;
	}

	public void setCodProdSuna(String codProdSuna) {
		this.codProdSuna = codProdSuna;
	}

	@Column(name = "des_deta_serv_bien", nullable = false, length = 500)
	public String getDesDetaServBien() {
		return this.desDetaServBien;
	}

	public void setDesDetaServBien(String desDetaServBien) {
		this.desDetaServBien = desDetaServBien;
	}

	@Column(name = "val_unit", nullable = false, length = 23)
	public String getValUnit() {
		return this.valUnit;
	}

	public void setValUnit(String valUnit) {
		this.valUnit = valUnit;
	}

	@Column(name = "tri_suma_trib_item", nullable = false, length = 15)
	public String getTriSumaTribItem() {
		return this.triSumaTribItem;
	}

	public void setTriSumaTribItem(String triSumaTribItem) {
		this.triSumaTribItem = triSumaTribItem;
	}

	@Column(name = "tri_codi_tipo_prod_igv", nullable = false, length = 4)
	public String getTriCodiTipoProdIgv() {
		return this.triCodiTipoProdIgv;
	}

	public void setTriCodiTipoProdIgv(String triCodiTipoProdIgv) {
		this.triCodiTipoProdIgv = triCodiTipoProdIgv;
	}

	@Column(name = "tri_mont_igv_item", nullable = false, length = 15)
	public String getTriMontIgvItem() {
		return this.triMontIgvItem;
	}

	public void setTriMontIgvItem(String triMontIgvItem) {
		this.triMontIgvItem = triMontIgvItem;
	}

	@Column(name = "tri_base_impo_igv_item", nullable = false, length = 15)
	public String getTriBaseImpoIgvItem() {
		return this.triBaseImpoIgvItem;
	}

	public void setTriBaseImpoIgvItem(String triBaseImpoIgvItem) {
		this.triBaseImpoIgvItem = triBaseImpoIgvItem;
	}

	@Column(name = "tri_nomb_trib_item", nullable = false, length = 4)
	public String getTriNombTribItem() {
		return this.triNombTribItem;
	}

	public void setTriNombTribItem(String triNombTribItem) {
		this.triNombTribItem = triNombTribItem;
	}

	@Column(name = "tri_codi_tipo_prod_item", nullable = false, length = 4)
	public String getTriCodiTipoProdItem() {
		return this.triCodiTipoProdItem;
	}

	public void setTriCodiTipoProdItem(String triCodiTipoProdItem) {
		this.triCodiTipoProdItem = triCodiTipoProdItem;
	}

	@Column(name = "tri_afec_igv_item", nullable = false, length = 2)
	public String getTriAfecIgvItem() {
		return this.triAfecIgvItem;
	}

	public void setTriAfecIgvItem(String triAfecIgvItem) {
		this.triAfecIgvItem = triAfecIgvItem;
	}

	@Column(name = "tri_porc_igv", nullable = false, length = 5)
	public String getTriPorcIgv() {
		return this.triPorcIgv;
	}

	public void setTriPorcIgv(String triPorcIgv) {
		this.triPorcIgv = triPorcIgv;
	}

	@Column(name = "tri_isc_codi_tipo_prod_isc", nullable = false, length = 4)
	public String getTriIscCodiTipoProdIsc() {
		return this.triIscCodiTipoProdIsc;
	}

	public void setTriIscCodiTipoProdIsc(String triIscCodiTipoProdIsc) {
		this.triIscCodiTipoProdIsc = triIscCodiTipoProdIsc;
	}

	@Column(name = "tri_isc_mont_isc_item", nullable = false, length = 15)
	public String getTriIscMontIscItem() {
		return this.triIscMontIscItem;
	}

	public void setTriIscMontIscItem(String triIscMontIscItem) {
		this.triIscMontIscItem = triIscMontIscItem;
	}

	@Column(name = "tri_isc_base_impo_isc_item", nullable = false, length = 15)
	public String getTriIscBaseImpoIscItem() {
		return this.triIscBaseImpoIscItem;
	}

	public void setTriIscBaseImpoIscItem(String triIscBaseImpoIscItem) {
		this.triIscBaseImpoIscItem = triIscBaseImpoIscItem;
	}

	@Column(name = "tri_isc_nomb_trib_item", nullable = false, length = 4)
	public String getTriIscNombTribItem() {
		return this.triIscNombTribItem;
	}

	public void setTriIscNombTribItem(String triIscNombTribItem) {
		this.triIscNombTribItem = triIscNombTribItem;
	}

	@Column(name = "tri_isc_codi_tipo_trib_item", nullable = false, length = 4)
	public String getTriIscCodiTipoTribItem() {
		return this.triIscCodiTipoTribItem;
	}

	public void setTriIscCodiTipoTribItem(String triIscCodiTipoTribItem) {
		this.triIscCodiTipoTribItem = triIscCodiTipoTribItem;
	}

	@Column(name = "tri_isc_tipo_sist_isc", length = 2)
	public String getTriIscTipoSistIsc() {
		return this.triIscTipoSistIsc;
	}

	public void setTriIscTipoSistIsc(String triIscTipoSistIsc) {
		this.triIscTipoSistIsc = triIscTipoSistIsc;
	}

	@Column(name = "tri_isc_porc_isc", nullable = false, length = 5)
	public String getTriIscPorcIsc() {
		return this.triIscPorcIsc;
	}

	public void setTriIscPorcIsc(String triIscPorcIsc) {
		this.triIscPorcIsc = triIscPorcIsc;
	}

	@Column(name = "tri_otro_codi_tipo_trib_otro", nullable = false, length = 4)
	public String getTriOtroCodiTipoTribOtro() {
		return this.triOtroCodiTipoTribOtro;
	}

	public void setTriOtroCodiTipoTribOtro(String triOtroCodiTipoTribOtro) {
		this.triOtroCodiTipoTribOtro = triOtroCodiTipoTribOtro;
	}

	@Column(name = "tri_otro_mont_trib_item", nullable = false, length = 15)
	public String getTriOtroMontTribItem() {
		return this.triOtroMontTribItem;
	}

	public void setTriOtroMontTribItem(String triOtroMontTribItem) {
		this.triOtroMontTribItem = triOtroMontTribItem;
	}

	@Column(name = "tri_otro_base_impo_trib_item", nullable = false, length = 15)
	public String getTriOtroBaseImpoTribItem() {
		return this.triOtroBaseImpoTribItem;
	}

	public void setTriOtroBaseImpoTribItem(String triOtroBaseImpoTribItem) {
		this.triOtroBaseImpoTribItem = triOtroBaseImpoTribItem;
	}

	@Column(name = "tri_otro_nomb_trib_item", nullable = false, length = 4)
	public String getTriOtroNombTribItem() {
		return this.triOtroNombTribItem;
	}

	public void setTriOtroNombTribItem(String triOtroNombTribItem) {
		this.triOtroNombTribItem = triOtroNombTribItem;
	}

	@Column(name = "tri_otro_codi_trib_item", nullable = false, length = 4)
	public String getTriOtroCodiTribItem() {
		return this.triOtroCodiTribItem;
	}

	public void setTriOtroCodiTribItem(String triOtroCodiTribItem) {
		this.triOtroCodiTribItem = triOtroCodiTribItem;
	}

	@Column(name = "tri_otro_porc_trib_item", nullable = false, length = 5)
	public String getTriOtroPorcTribItem() {
		return this.triOtroPorcTribItem;
	}

	public void setTriOtroPorcTribItem(String triOtroPorcTribItem) {
		this.triOtroPorcTribItem = triOtroPorcTribItem;
	}

	@Column(name = "pre_vent_unit", nullable = false, length = 23)
	public String getPreVentUnit() {
		return this.preVentUnit;
	}

	public void setPreVentUnit(String preVentUnit) {
		this.preVentUnit = preVentUnit;
	}

	@Column(name = "val_vent_item", nullable = false, length = 15)
	public String getValVentItem() {
		return this.valVentItem;
	}

	public void setValVentItem(String valVentItem) {
		this.valVentItem = valVentItem;
	}

	@Column(name = "val_refe_unit_grat", length = 15)
	public String getValRefeUnitGrat() {
		return this.valRefeUnitGrat;
	}

	public void setValRefeUnitGrat(String valRefeUnitGrat) {
		this.valRefeUnitGrat = valRefeUnitGrat;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
