package hibernate.entidades;
// Generated 12/09/2019 12:32:03 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpProvi generated by hbm2java
 */
@Entity
@Table(name = "tp_provi", schema = "public")
public class TpProvi implements java.io.Serializable {

	private Integer codProv;
	private TpDepar tpDepar;
	private String desProv;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpProvi() {
	}

	public TpProvi(Integer codProv, TpDepar tpDepar, String desProv, Integer indEsta, String usuApliCrea,
			Date fecCreaRegi) {
		this.codProv = codProv;
		this.tpDepar = tpDepar;
		this.desProv = desProv;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpProvi(Integer codProv, TpDepar tpDepar, String desProv, Integer indEsta, String usuApliCrea,
			Date fecCreaRegi, String usuApliModi, Date fecModiRegi) {
		this.codProv = codProv;
		this.tpDepar = tpDepar;
		this.desProv = desProv;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_prov", unique = true, nullable = false)
	public Integer getCodProv() {
		return this.codProv;
	}

	public void setCodProv(Integer codProv) {
		this.codProv = codProv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_depa", nullable = false)
	public TpDepar getTpDepar() {
		return this.tpDepar;
	}

	public void setTpDepar(TpDepar tpDepar) {
		this.tpDepar = tpDepar;
	}

	@Column(name = "des_prov", nullable = false, length = 50)
	public String getDesProv() {
		return this.desProv;
	}

	public void setDesProv(String desProv) {
		this.desProv = desProv;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
