package dto;
// Generated 11/11/2018 07:01:03 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * TpParamGener generated by hbm2java
 */

public class TpParamGenerDto implements java.io.Serializable {

	private static final long serialVersionUID = 2319659582821369929L;
	
	private Integer codParaGene;
	private String nomParaGene;
	private String valParaGene;
	private String desValoParaGene;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpParamGenerDto() {
	}

	public Integer getCodParaGene() {
		return codParaGene;
	}

	public void setCodParaGene(Integer codParaGene) {
		this.codParaGene = codParaGene;
	}

	public String getNomParaGene() {
		return nomParaGene;
	}

	public void setNomParaGene(String nomParaGene) {
		this.nomParaGene = nomParaGene;
	}

	public String getValParaGene() {
		return valParaGene;
	}

	public void setValParaGene(String valParaGene) {
		this.valParaGene = valParaGene;
	}

	public String getDesValoParaGene() {
		return desValoParaGene;
	}

	public void setDesValoParaGene(String desValoParaGene) {
		this.desValoParaGene = desValoParaGene;
	}

	public Integer getIndEsta() {
		return indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	public String getUsuApliCrea() {
		return usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	public Date getFecCreaRegi() {
		return fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	public String getUsuApliModi() {
		return usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	public Date getFecModiRegi() {
		return fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

	
}
