package hibernate.entidades;
// Generated 12/09/2019 12:32:03 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpDivis generated by hbm2java
 */
@Entity
@Table(name = "tp_divis", schema = "public")
public class TpDivis implements java.io.Serializable {

	private Integer codDivi;
	private String codIsoDivi;
	private String nomDiviSing;
	private String nomDiviPlur;
	private String simDivi;
	private Integer indApliCuenBanc;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpDivis() {
	}

	public TpDivis(Integer codDivi, String codIsoDivi, String nomDiviSing, Integer indApliCuenBanc, Integer indEsta,
			String usuApliCrea, Date fecCreaRegi) {
		this.codDivi = codDivi;
		this.codIsoDivi = codIsoDivi;
		this.nomDiviSing = nomDiviSing;
		this.indApliCuenBanc = indApliCuenBanc;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpDivis(Integer codDivi, String codIsoDivi, String nomDiviSing, String nomDiviPlur, String simDivi,
			Integer indApliCuenBanc, Integer indEsta, String usuApliCrea, Date fecCreaRegi, String usuApliModi,
			Date fecModiRegi) {
		this.codDivi = codDivi;
		this.codIsoDivi = codIsoDivi;
		this.nomDiviSing = nomDiviSing;
		this.nomDiviPlur = nomDiviPlur;
		this.simDivi = simDivi;
		this.indApliCuenBanc = indApliCuenBanc;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_divi", unique = true, nullable = false)
	public Integer getCodDivi() {
		return this.codDivi;
	}

	public void setCodDivi(Integer codDivi) {
		this.codDivi = codDivi;
	}

	@Column(name = "cod_iso_divi", nullable = false, length = 5)
	public String getCodIsoDivi() {
		return this.codIsoDivi;
	}

	public void setCodIsoDivi(String codIsoDivi) {
		this.codIsoDivi = codIsoDivi;
	}

	@Column(name = "nom_divi_sing", nullable = false, length = 100)
	public String getNomDiviSing() {
		return this.nomDiviSing;
	}

	public void setNomDiviSing(String nomDiviSing) {
		this.nomDiviSing = nomDiviSing;
	}

	@Column(name = "nom_divi_plur", length = 100)
	public String getNomDiviPlur() {
		return this.nomDiviPlur;
	}

	public void setNomDiviPlur(String nomDiviPlur) {
		this.nomDiviPlur = nomDiviPlur;
	}

	@Column(name = "sim_divi", length = 5)
	public String getSimDivi() {
		return this.simDivi;
	}

	public void setSimDivi(String simDivi) {
		this.simDivi = simDivi;
	}

	@Column(name = "ind_apli_cuen_banc", nullable = false)
	public Integer getIndApliCuenBanc() {
		return this.indApliCuenBanc;
	}

	public void setIndApliCuenBanc(Integer indApliCuenBanc) {
		this.indApliCuenBanc = indApliCuenBanc;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
