package hibernate.entidades;
// Generated 12/09/2019 12:32:03 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpFactDocumCabec generated by hbm2java
 */
@Entity
@Table(name = "tp_fact_docum_cabec", schema = "public")
public class TpFactDocumCabec implements java.io.Serializable {

	private Integer codFactDocuCabec;
	private String tipOper;
	private String fecEmis;
	private String horEmis;
	private String fecVenc;
	private String codDomiFisc;
	private String tipDocuIden;
	private String numDocuIden;
	private String nomRazoSociUsua;
	private String tipMone;
	private String sumTrib;
	private String totValoVent;
	private String totPrecVent;
	private String totDesc;
	private String sumOtroCarg;
	private String totAnti;
	private String impTotaVent;
	private String verUbl;
	private String cusDocu;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpFactDocumCabec() {
	}

	public TpFactDocumCabec(Integer codFactDocuCabec, String tipOper, String fecEmis, String horEmis, String tipMone,
			String sumTrib, String totValoVent, String impTotaVent, String verUbl, String cusDocu, Integer indEsta,
			String usuApliCrea, Date fecCreaRegi) {
		this.codFactDocuCabec = codFactDocuCabec;
		this.tipOper = tipOper;
		this.fecEmis = fecEmis;
		this.horEmis = horEmis;
		this.tipMone = tipMone;
		this.sumTrib = sumTrib;
		this.totValoVent = totValoVent;
		this.impTotaVent = impTotaVent;
		this.verUbl = verUbl;
		this.cusDocu = cusDocu;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpFactDocumCabec(Integer codFactDocuCabec, String tipOper, String fecEmis, String horEmis, String fecVenc,
			String codDomiFisc, String tipDocuIden, String numDocuIden, String nomRazoSociUsua, String tipMone,
			String sumTrib, String totValoVent, String totPrecVent, String totDesc, String sumOtroCarg, String totAnti,
			String impTotaVent, String verUbl, String cusDocu, Integer indEsta, String usuApliCrea, Date fecCreaRegi,
			String usuApliModi, Date fecModiRegi) {
		this.codFactDocuCabec = codFactDocuCabec;
		this.tipOper = tipOper;
		this.fecEmis = fecEmis;
		this.horEmis = horEmis;
		this.fecVenc = fecVenc;
		this.codDomiFisc = codDomiFisc;
		this.tipDocuIden = tipDocuIden;
		this.numDocuIden = numDocuIden;
		this.nomRazoSociUsua = nomRazoSociUsua;
		this.tipMone = tipMone;
		this.sumTrib = sumTrib;
		this.totValoVent = totValoVent;
		this.totPrecVent = totPrecVent;
		this.totDesc = totDesc;
		this.sumOtroCarg = sumOtroCarg;
		this.totAnti = totAnti;
		this.impTotaVent = impTotaVent;
		this.verUbl = verUbl;
		this.cusDocu = cusDocu;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_fact_docu_cabec", unique = true, nullable = false)
	public Integer getCodFactDocuCabec() {
		return this.codFactDocuCabec;
	}

	public void setCodFactDocuCabec(Integer codFactDocuCabec) {
		this.codFactDocuCabec = codFactDocuCabec;
	}

	@Column(name = "tip_oper", nullable = false, length = 4)
	public String getTipOper() {
		return this.tipOper;
	}

	public void setTipOper(String tipOper) {
		this.tipOper = tipOper;
	}

	@Column(name = "fec_emis", nullable = false, length = 10)
	public String getFecEmis() {
		return this.fecEmis;
	}

	public void setFecEmis(String fecEmis) {
		this.fecEmis = fecEmis;
	}

	@Column(name = "hor_emis", nullable = false, length = 14)
	public String getHorEmis() {
		return this.horEmis;
	}

	public void setHorEmis(String horEmis) {
		this.horEmis = horEmis;
	}

	@Column(name = "fec_venc", length = 10)
	public String getFecVenc() {
		return this.fecVenc;
	}

	public void setFecVenc(String fecVenc) {
		this.fecVenc = fecVenc;
	}

	@Column(name = "cod_domi_fisc", length = 3)
	public String getCodDomiFisc() {
		return this.codDomiFisc;
	}

	public void setCodDomiFisc(String codDomiFisc) {
		this.codDomiFisc = codDomiFisc;
	}

	@Column(name = "tip_docu_iden", length = 1)
	public String getTipDocuIden() {
		return this.tipDocuIden;
	}

	public void setTipDocuIden(String tipDocuIden) {
		this.tipDocuIden = tipDocuIden;
	}

	@Column(name = "num_docu_iden", length = 15)
	public String getNumDocuIden() {
		return this.numDocuIden;
	}

	public void setNumDocuIden(String numDocuIden) {
		this.numDocuIden = numDocuIden;
	}

	@Column(name = "nom_razo_soci_usua", length = 1500)
	public String getNomRazoSociUsua() {
		return this.nomRazoSociUsua;
	}

	public void setNomRazoSociUsua(String nomRazoSociUsua) {
		this.nomRazoSociUsua = nomRazoSociUsua;
	}

	@Column(name = "tip_mone", nullable = false, length = 3)
	public String getTipMone() {
		return this.tipMone;
	}

	public void setTipMone(String tipMone) {
		this.tipMone = tipMone;
	}

	@Column(name = "sum_trib", nullable = false, length = 15)
	public String getSumTrib() {
		return this.sumTrib;
	}

	public void setSumTrib(String sumTrib) {
		this.sumTrib = sumTrib;
	}

	@Column(name = "tot_valo_vent", nullable = false, length = 15)
	public String getTotValoVent() {
		return this.totValoVent;
	}

	public void setTotValoVent(String totValoVent) {
		this.totValoVent = totValoVent;
	}

	@Column(name = "tot_prec_vent", length = 15)
	public String getTotPrecVent() {
		return this.totPrecVent;
	}

	public void setTotPrecVent(String totPrecVent) {
		this.totPrecVent = totPrecVent;
	}

	@Column(name = "tot_desc", length = 15)
	public String getTotDesc() {
		return this.totDesc;
	}

	public void setTotDesc(String totDesc) {
		this.totDesc = totDesc;
	}

	@Column(name = "sum_otro_carg", length = 15)
	public String getSumOtroCarg() {
		return this.sumOtroCarg;
	}

	public void setSumOtroCarg(String sumOtroCarg) {
		this.sumOtroCarg = sumOtroCarg;
	}

	@Column(name = "tot_anti", length = 15)
	public String getTotAnti() {
		return this.totAnti;
	}

	public void setTotAnti(String totAnti) {
		this.totAnti = totAnti;
	}

	@Column(name = "imp_tota_vent", nullable = false, length = 15)
	public String getImpTotaVent() {
		return this.impTotaVent;
	}

	public void setImpTotaVent(String impTotaVent) {
		this.impTotaVent = impTotaVent;
	}

	@Column(name = "ver_ubl", nullable = false, length = 3)
	public String getVerUbl() {
		return this.verUbl;
	}

	public void setVerUbl(String verUbl) {
		this.verUbl = verUbl;
	}

	@Column(name = "cus_docu", nullable = false, length = 3)
	public String getCusDocu() {
		return this.cusDocu;
	}

	public void setCusDocu(String cusDocu) {
		this.cusDocu = cusDocu;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
