package hibernate.entidades;
// Generated 12/09/2019 12:32:03 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpTipoPerso generated by hbm2java
 */
@Entity
@Table(name = "tp_tipo_perso", schema = "public")
public class TpTipoPerso implements java.io.Serializable {

	private Integer codTipoPers;
	private String desTipoPers;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpTipoPerso() {
	}

	public TpTipoPerso(Integer codTipoPers, String desTipoPers, Integer indEsta, String usuApliCrea, Date fecCreaRegi) {
		this.codTipoPers = codTipoPers;
		this.desTipoPers = desTipoPers;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpTipoPerso(Integer codTipoPers, String desTipoPers, Integer indEsta, String usuApliCrea, Date fecCreaRegi,
			String usuApliModi, Date fecModiRegi) {
		this.codTipoPers = codTipoPers;
		this.desTipoPers = desTipoPers;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_tipo_pers", unique = true, nullable = false)
	public Integer getCodTipoPers() {
		return this.codTipoPers;
	}

	public void setCodTipoPers(Integer codTipoPers) {
		this.codTipoPers = codTipoPers;
	}

	@Column(name = "des_tipo_pers", nullable = false, length = 50)
	public String getDesTipoPers() {
		return this.desTipoPers;
	}

	public void setDesTipoPers(String desTipoPers) {
		this.desTipoPers = desTipoPers;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
