package hibernate.entidades;
// Generated 12/09/2019 12:32:03 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AudiTpTipoCambi generated by hbm2java
 */
@Entity
@Table(name = "audi_tp_tipo_cambi", schema = "public")
public class AudiTpTipoCambi implements java.io.Serializable {

	private Integer codAudiTipoCamb;
	private Integer codTipoCamb;
	private Integer codDivi;
	private Integer codDiviCamb;
	private Double valCambComp;
	private Double valCambVent;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public AudiTpTipoCambi() {
	}

	public AudiTpTipoCambi(Integer codAudiTipoCamb, Integer codTipoCamb, Integer codDivi, Integer codDiviCamb,
			Double valCambComp, Double valCambVent, Integer indEsta, String usuApliCrea, Date fecCreaRegi) {
		this.codAudiTipoCamb = codAudiTipoCamb;
		this.codTipoCamb = codTipoCamb;
		this.codDivi = codDivi;
		this.codDiviCamb = codDiviCamb;
		this.valCambComp = valCambComp;
		this.valCambVent = valCambVent;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public AudiTpTipoCambi(Integer codAudiTipoCamb, Integer codTipoCamb, Integer codDivi, Integer codDiviCamb,
			Double valCambComp, Double valCambVent, Integer indEsta, String usuApliCrea, Date fecCreaRegi,
			String usuApliModi, Date fecModiRegi) {
		this.codAudiTipoCamb = codAudiTipoCamb;
		this.codTipoCamb = codTipoCamb;
		this.codDivi = codDivi;
		this.codDiviCamb = codDiviCamb;
		this.valCambComp = valCambComp;
		this.valCambVent = valCambVent;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_audi_tipo_camb", unique = true, nullable = false)
	public Integer getCodAudiTipoCamb() {
		return this.codAudiTipoCamb;
	}

	public void setCodAudiTipoCamb(Integer codAudiTipoCamb) {
		this.codAudiTipoCamb = codAudiTipoCamb;
	}

	@Column(name = "cod_tipo_camb", nullable = false)
	public Integer getCodTipoCamb() {
		return this.codTipoCamb;
	}

	public void setCodTipoCamb(Integer codTipoCamb) {
		this.codTipoCamb = codTipoCamb;
	}

	@Column(name = "cod_divi", nullable = false)
	public Integer getCodDivi() {
		return this.codDivi;
	}

	public void setCodDivi(Integer codDivi) {
		this.codDivi = codDivi;
	}

	@Column(name = "cod_divi_camb", nullable = false)
	public Integer getCodDiviCamb() {
		return this.codDiviCamb;
	}

	public void setCodDiviCamb(Integer codDiviCamb) {
		this.codDiviCamb = codDiviCamb;
	}

	@Column(name = "val_camb_comp", nullable = false, precision = 17, scale = 17)
	public Double getValCambComp() {
		return this.valCambComp;
	}

	public void setValCambComp(Double valCambComp) {
		this.valCambComp = valCambComp;
	}

	@Column(name = "val_camb_vent", nullable = false, precision = 17, scale = 17)
	public Double getValCambVent() {
		return this.valCambVent;
	}

	public void setValCambVent(Double valCambVent) {
		this.valCambVent = valCambVent;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
