package hibernate.entidades;
// Generated 26 jun. 2021 03:16:16 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TpOperaClien generated by hbm2java
 */
@Entity
@Table(name = "tp_opera_clien", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "cod_unic_oper_clie"))
public class TpOperaClien implements java.io.Serializable {

	private Integer codOperClie;
	private TpClien tpClien;
	private TpCuentBanco tpCuentBancoByCodCuenBancClieReci;
	private TpCuentBanco tpCuentBancoByCodCuenBancCome;
	private TpCuentBanco tpCuentBancoByCodCuenBancClieOrig;
	private TpDivis tpDivisByCodDiviEnvi;
	private TpDivis tpDivisByCodDiviReci;
	private TpEstadOpera tpEstadOpera;
	private TpOrigeFondo tpOrigeFondo;
	private TpTipoCambi tpTipoCambi;
	private String codUnicOperClie;
	private BigDecimal monEnvi;
	private BigDecimal monReci;
	private Integer indCompVent;
	private Double valTipoCambUsad;
	private String codTranBanc;
	private Date fecInicOper;
	private Date fecVeriOper;
	private Date fecFinaOper;
	private String usuApliFinaOper;
	private Date fecCancOper;
	private String usuApliCancOper;
	private String valTextComeCanc;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpOperaClien() {
		tpClien = new TpClien();
		tpCuentBancoByCodCuenBancClieReci = new TpCuentBanco();
		tpCuentBancoByCodCuenBancCome = new TpCuentBanco();
		tpCuentBancoByCodCuenBancClieOrig = new TpCuentBanco();
		tpDivisByCodDiviReci = new TpDivis();
		tpDivisByCodDiviEnvi = new TpDivis();
		tpEstadOpera = new TpEstadOpera();
		tpTipoCambi = new TpTipoCambi();
		tpOrigeFondo = new TpOrigeFondo();
	}

	public TpOperaClien(Integer codOperClie, TpClien tpClien, TpCuentBanco tpCuentBancoByCodCuenBancClieReci,
			TpCuentBanco tpCuentBancoByCodCuenBancCome, TpCuentBanco tpCuentBancoByCodCuenBancClieOrig,
			TpDivis tpDivisByCodDiviEnvi, TpDivis tpDivisByCodDiviReci, TpEstadOpera tpEstadOpera,
			TpTipoCambi tpTipoCambi, BigDecimal monEnvi, BigDecimal monReci, Integer indCompVent,
			Double valTipoCambUsad, Integer indEsta, String usuApliCrea, Date fecCreaRegi) {
		this.codOperClie = codOperClie;
		this.tpClien = tpClien;
		this.tpCuentBancoByCodCuenBancClieReci = tpCuentBancoByCodCuenBancClieReci;
		this.tpCuentBancoByCodCuenBancCome = tpCuentBancoByCodCuenBancCome;
		this.tpCuentBancoByCodCuenBancClieOrig = tpCuentBancoByCodCuenBancClieOrig;
		this.tpDivisByCodDiviEnvi = tpDivisByCodDiviEnvi;
		this.tpDivisByCodDiviReci = tpDivisByCodDiviReci;
		this.tpEstadOpera = tpEstadOpera;
		this.tpTipoCambi = tpTipoCambi;
		this.monEnvi = monEnvi;
		this.monReci = monReci;
		this.indCompVent = indCompVent;
		this.valTipoCambUsad = valTipoCambUsad;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpOperaClien(Integer codOperClie, TpClien tpClien, TpCuentBanco tpCuentBancoByCodCuenBancClieReci,
			TpCuentBanco tpCuentBancoByCodCuenBancCome, TpCuentBanco tpCuentBancoByCodCuenBancClieOrig,
			TpDivis tpDivisByCodDiviEnvi, TpDivis tpDivisByCodDiviReci, TpEstadOpera tpEstadOpera,
			TpOrigeFondo tpOrigeFondo, TpTipoCambi tpTipoCambi, String codUnicOperClie, BigDecimal monEnvi,
			BigDecimal monReci, Integer indCompVent, Double valTipoCambUsad, String codTranBanc, Date fecInicOper,
			Date fecVeriOper, Date fecFinaOper, String usuApliFinaOper, Date fecCancOper, String usuApliCancOper,
			String valTextComeCanc, Integer indEsta, String usuApliCrea, Date fecCreaRegi, String usuApliModi,
			Date fecModiRegi) {
		this.codOperClie = codOperClie;
		this.tpClien = tpClien;
		this.tpCuentBancoByCodCuenBancClieReci = tpCuentBancoByCodCuenBancClieReci;
		this.tpCuentBancoByCodCuenBancCome = tpCuentBancoByCodCuenBancCome;
		this.tpCuentBancoByCodCuenBancClieOrig = tpCuentBancoByCodCuenBancClieOrig;
		this.tpDivisByCodDiviEnvi = tpDivisByCodDiviEnvi;
		this.tpDivisByCodDiviReci = tpDivisByCodDiviReci;
		this.tpEstadOpera = tpEstadOpera;
		this.tpOrigeFondo = tpOrigeFondo;
		this.tpTipoCambi = tpTipoCambi;
		this.codUnicOperClie = codUnicOperClie;
		this.monEnvi = monEnvi;
		this.monReci = monReci;
		this.indCompVent = indCompVent;
		this.valTipoCambUsad = valTipoCambUsad;
		this.codTranBanc = codTranBanc;
		this.fecInicOper = fecInicOper;
		this.fecVeriOper = fecVeriOper;
		this.fecFinaOper = fecFinaOper;
		this.usuApliFinaOper = usuApliFinaOper;
		this.fecCancOper = fecCancOper;
		this.usuApliCancOper = usuApliCancOper;
		this.valTextComeCanc = valTextComeCanc;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_oper_clie", unique = true, nullable = false)
	public Integer getCodOperClie() {
		return this.codOperClie;
	}

	public void setCodOperClie(Integer codOperClie) {
		this.codOperClie = codOperClie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_clie", nullable = false)
	public TpClien getTpClien() {
		return this.tpClien;
	}

	public void setTpClien(TpClien tpClien) {
		this.tpClien = tpClien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_cuen_banc_clie_reci", nullable = false)
	public TpCuentBanco getTpCuentBancoByCodCuenBancClieReci() {
		return this.tpCuentBancoByCodCuenBancClieReci;
	}

	public void setTpCuentBancoByCodCuenBancClieReci(TpCuentBanco tpCuentBancoByCodCuenBancClieReci) {
		this.tpCuentBancoByCodCuenBancClieReci = tpCuentBancoByCodCuenBancClieReci;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_cuen_banc_come", nullable = false)
	public TpCuentBanco getTpCuentBancoByCodCuenBancCome() {
		return this.tpCuentBancoByCodCuenBancCome;
	}

	public void setTpCuentBancoByCodCuenBancCome(TpCuentBanco tpCuentBancoByCodCuenBancCome) {
		this.tpCuentBancoByCodCuenBancCome = tpCuentBancoByCodCuenBancCome;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_cuen_banc_clie_orig", nullable = false)
	public TpCuentBanco getTpCuentBancoByCodCuenBancClieOrig() {
		return this.tpCuentBancoByCodCuenBancClieOrig;
	}

	public void setTpCuentBancoByCodCuenBancClieOrig(TpCuentBanco tpCuentBancoByCodCuenBancClieOrig) {
		this.tpCuentBancoByCodCuenBancClieOrig = tpCuentBancoByCodCuenBancClieOrig;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_divi_envi", nullable = false)
	public TpDivis getTpDivisByCodDiviEnvi() {
		return this.tpDivisByCodDiviEnvi;
	}

	public void setTpDivisByCodDiviEnvi(TpDivis tpDivisByCodDiviEnvi) {
		this.tpDivisByCodDiviEnvi = tpDivisByCodDiviEnvi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_divi_reci", nullable = false)
	public TpDivis getTpDivisByCodDiviReci() {
		return this.tpDivisByCodDiviReci;
	}

	public void setTpDivisByCodDiviReci(TpDivis tpDivisByCodDiviReci) {
		this.tpDivisByCodDiviReci = tpDivisByCodDiviReci;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_esta_oper", nullable = false)
	public TpEstadOpera getTpEstadOpera() {
		return this.tpEstadOpera;
	}

	public void setTpEstadOpera(TpEstadOpera tpEstadOpera) {
		this.tpEstadOpera = tpEstadOpera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_orig_fond")
	public TpOrigeFondo getTpOrigeFondo() {
		return this.tpOrigeFondo;
	}

	public void setTpOrigeFondo(TpOrigeFondo tpOrigeFondo) {
		this.tpOrigeFondo = tpOrigeFondo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tipo_camb", nullable = false)
	public TpTipoCambi getTpTipoCambi() {
		return this.tpTipoCambi;
	}

	public void setTpTipoCambi(TpTipoCambi tpTipoCambi) {
		this.tpTipoCambi = tpTipoCambi;
	}

	@Column(name = "cod_unic_oper_clie", unique = true, length = 9)
	public String getCodUnicOperClie() {
		return this.codUnicOperClie;
	}

	public void setCodUnicOperClie(String codUnicOperClie) {
		this.codUnicOperClie = codUnicOperClie;
	}

	@Column(name = "mon_envi", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getMonEnvi() {
		return this.monEnvi;
	}

	public void setMonEnvi(BigDecimal monEnvi) {
		this.monEnvi = monEnvi;
	}

	@Column(name = "mon_reci", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getMonReci() {
		return this.monReci;
	}

	public void setMonReci(BigDecimal monReci) {
		this.monReci = monReci;
	}

	@Column(name = "ind_comp_vent", nullable = false)
	public Integer getIndCompVent() {
		return this.indCompVent;
	}

	public void setIndCompVent(Integer indCompVent) {
		this.indCompVent = indCompVent;
	}

	@Column(name = "val_tipo_camb_usad", nullable = false, precision = 17, scale = 17)
	public Double getValTipoCambUsad() {
		return this.valTipoCambUsad;
	}

	public void setValTipoCambUsad(Double valTipoCambUsad) {
		this.valTipoCambUsad = valTipoCambUsad;
	}

	@Column(name = "cod_tran_banc", length = 40)
	public String getCodTranBanc() {
		return this.codTranBanc;
	}

	public void setCodTranBanc(String codTranBanc) {
		this.codTranBanc = codTranBanc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_inic_oper", length = 29)
	public Date getFecInicOper() {
		return this.fecInicOper;
	}

	public void setFecInicOper(Date fecInicOper) {
		this.fecInicOper = fecInicOper;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_veri_oper", length = 29)
	public Date getFecVeriOper() {
		return this.fecVeriOper;
	}

	public void setFecVeriOper(Date fecVeriOper) {
		this.fecVeriOper = fecVeriOper;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_fina_oper", length = 29)
	public Date getFecFinaOper() {
		return this.fecFinaOper;
	}

	public void setFecFinaOper(Date fecFinaOper) {
		this.fecFinaOper = fecFinaOper;
	}

	@Column(name = "usu_apli_fina_oper", length = 100)
	public String getUsuApliFinaOper() {
		return this.usuApliFinaOper;
	}

	public void setUsuApliFinaOper(String usuApliFinaOper) {
		this.usuApliFinaOper = usuApliFinaOper;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_canc_oper", length = 29)
	public Date getFecCancOper() {
		return this.fecCancOper;
	}

	public void setFecCancOper(Date fecCancOper) {
		this.fecCancOper = fecCancOper;
	}

	@Column(name = "usu_apli_canc_oper", length = 100)
	public String getUsuApliCancOper() {
		return this.usuApliCancOper;
	}

	public void setUsuApliCancOper(String usuApliCancOper) {
		this.usuApliCancOper = usuApliCancOper;
	}

	@Column(name = "val_text_come_canc", length = 150)
	public String getValTextComeCanc() {
		return this.valTextComeCanc;
	}

	public void setValTextComeCanc(String valTextComeCanc) {
		this.valTextComeCanc = valTextComeCanc;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
