package hibernate.entidades;
// Generated 31/01/2021 03:09:10 PM by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpReclaQueja generated by hbm2java
 */
@Entity
@Table(name = "tp_recla_queja", schema = "public")
public class TpReclaQueja implements java.io.Serializable {

	private Integer codReclQuej;
	private TpTipoDocumPerso tpTipoDocumPerso;
	private TpTipoPerso tpTipoPerso;
	private String valNombPers;
	private String valApelPers;
	private String valRazoSociPers;
	private String valDocuEmpr;
	private String valDocuPers;
	private String valEmaiCont;
	private String valCeluCont;
	private String valTipoServCont;
	private BigDecimal valMontCamb;
	private String codUnicOperClie;
	private String valTipoReclQuej;
	private String valDescReclQuej;
	private Integer indEsta;
	private String usuApliCrea;
	private Date fecCreaRegi;
	private String usuApliModi;
	private Date fecModiRegi;

	public TpReclaQueja() {
		tpTipoDocumPerso = new TpTipoDocumPerso();
		tpTipoPerso = new TpTipoPerso();
	}

	public TpReclaQueja(Integer codReclQuej, TpTipoDocumPerso tpTipoDocumPerso, TpTipoPerso tpTipoPerso,
			String valNombPers, String valDocuPers, String valEmaiCont, String valCeluCont, String valTipoServCont,
			String valTipoReclQuej, String valDescReclQuej, Integer indEsta, String usuApliCrea, Date fecCreaRegi) {
		this.codReclQuej = codReclQuej;
		this.tpTipoDocumPerso = tpTipoDocumPerso;
		this.tpTipoPerso = tpTipoPerso;
		this.valNombPers = valNombPers;
		this.valDocuPers = valDocuPers;
		this.valEmaiCont = valEmaiCont;
		this.valCeluCont = valCeluCont;
		this.valTipoServCont = valTipoServCont;
		this.valTipoReclQuej = valTipoReclQuej;
		this.valDescReclQuej = valDescReclQuej;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
	}

	public TpReclaQueja(Integer codReclQuej, TpTipoDocumPerso tpTipoDocumPerso, TpTipoPerso tpTipoPerso,
			String valNombPers, String valApelPers, String valRazoSociPers, String valDocuEmpr, String valDocuPers,
			String valEmaiCont, String valCeluCont, String valTipoServCont, BigDecimal valMontCamb,
			String codUnicOperClie, String valTipoReclQuej, String valDescReclQuej, Integer indEsta, String usuApliCrea,
			Date fecCreaRegi, String usuApliModi, Date fecModiRegi) {
		this.codReclQuej = codReclQuej;
		this.tpTipoDocumPerso = tpTipoDocumPerso;
		this.tpTipoPerso = tpTipoPerso;
		this.valNombPers = valNombPers;
		this.valApelPers = valApelPers;
		this.valRazoSociPers = valRazoSociPers;
		this.valDocuEmpr = valDocuEmpr;
		this.valDocuPers = valDocuPers;
		this.valEmaiCont = valEmaiCont;
		this.valCeluCont = valCeluCont;
		this.valTipoServCont = valTipoServCont;
		this.valMontCamb = valMontCamb;
		this.codUnicOperClie = codUnicOperClie;
		this.valTipoReclQuej = valTipoReclQuej;
		this.valDescReclQuej = valDescReclQuej;
		this.indEsta = indEsta;
		this.usuApliCrea = usuApliCrea;
		this.fecCreaRegi = fecCreaRegi;
		this.usuApliModi = usuApliModi;
		this.fecModiRegi = fecModiRegi;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cod_recl_quej", unique = true, nullable = false)
	public Integer getCodReclQuej() {
		return this.codReclQuej;
	}

	public void setCodReclQuej(Integer codReclQuej) {
		this.codReclQuej = codReclQuej;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tipo_docu_pers", nullable = false)
	public TpTipoDocumPerso getTpTipoDocumPerso() {
		return this.tpTipoDocumPerso;
	}

	public void setTpTipoDocumPerso(TpTipoDocumPerso tpTipoDocumPerso) {
		this.tpTipoDocumPerso = tpTipoDocumPerso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tipo_pers", nullable = false)
	public TpTipoPerso getTpTipoPerso() {
		return this.tpTipoPerso;
	}

	public void setTpTipoPerso(TpTipoPerso tpTipoPerso) {
		this.tpTipoPerso = tpTipoPerso;
	}

	@Column(name = "val_nomb_pers", nullable = false, length = 100)
	public String getValNombPers() {
		return this.valNombPers;
	}

	public void setValNombPers(String valNombPers) {
		this.valNombPers = valNombPers;
	}

	@Column(name = "val_apel_pers", length = 100)
	public String getValApelPers() {
		return this.valApelPers;
	}

	public void setValApelPers(String valApelPers) {
		this.valApelPers = valApelPers;
	}

	@Column(name = "val_razo_soci_pers", length = 200)
	public String getValRazoSociPers() {
		return this.valRazoSociPers;
	}

	public void setValRazoSociPers(String valRazoSociPers) {
		this.valRazoSociPers = valRazoSociPers;
	}

	@Column(name = "val_docu_empr", length = 50)
	public String getValDocuEmpr() {
		return this.valDocuEmpr;
	}

	public void setValDocuEmpr(String valDocuEmpr) {
		this.valDocuEmpr = valDocuEmpr;
	}

	@Column(name = "val_docu_pers", nullable = false, length = 50)
	public String getValDocuPers() {
		return this.valDocuPers;
	}

	public void setValDocuPers(String valDocuPers) {
		this.valDocuPers = valDocuPers;
	}

	@Column(name = "val_emai_cont", nullable = false, length = 100)
	public String getValEmaiCont() {
		return this.valEmaiCont;
	}

	public void setValEmaiCont(String valEmaiCont) {
		this.valEmaiCont = valEmaiCont;
	}

	@Column(name = "val_celu_cont", nullable = false, length = 20)
	public String getValCeluCont() {
		return this.valCeluCont;
	}

	public void setValCeluCont(String valCeluCont) {
		this.valCeluCont = valCeluCont;
	}

	@Column(name = "val_tipo_serv_cont", nullable = false, length = 50)
	public String getValTipoServCont() {
		return this.valTipoServCont;
	}

	public void setValTipoServCont(String valTipoServCont) {
		this.valTipoServCont = valTipoServCont;
	}

	@Column(name = "val_mont_camb", precision = 131089, scale = 0)
	public BigDecimal getValMontCamb() {
		return this.valMontCamb;
	}

	public void setValMontCamb(BigDecimal valMontCamb) {
		this.valMontCamb = valMontCamb;
	}

	@Column(name = "cod_unic_oper_clie", length = 9)
	public String getCodUnicOperClie() {
		return this.codUnicOperClie;
	}

	public void setCodUnicOperClie(String codUnicOperClie) {
		this.codUnicOperClie = codUnicOperClie;
	}

	@Column(name = "val_tipo_recl_quej", nullable = false, length = 40)
	public String getValTipoReclQuej() {
		return this.valTipoReclQuej;
	}

	public void setValTipoReclQuej(String valTipoReclQuej) {
		this.valTipoReclQuej = valTipoReclQuej;
	}

	@Column(name = "val_desc_recl_quej", nullable = false, length = 600)
	public String getValDescReclQuej() {
		return this.valDescReclQuej;
	}

	public void setValDescReclQuej(String valDescReclQuej) {
		this.valDescReclQuej = valDescReclQuej;
	}

	@Column(name = "ind_esta", nullable = false)
	public Integer getIndEsta() {
		return this.indEsta;
	}

	public void setIndEsta(Integer indEsta) {
		this.indEsta = indEsta;
	}

	@Column(name = "usu_apli_crea", nullable = false, length = 100)
	public String getUsuApliCrea() {
		return this.usuApliCrea;
	}

	public void setUsuApliCrea(String usuApliCrea) {
		this.usuApliCrea = usuApliCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_crea_regi", nullable = false, length = 29)
	public Date getFecCreaRegi() {
		return this.fecCreaRegi;
	}

	public void setFecCreaRegi(Date fecCreaRegi) {
		this.fecCreaRegi = fecCreaRegi;
	}

	@Column(name = "usu_apli_modi", length = 100)
	public String getUsuApliModi() {
		return this.usuApliModi;
	}

	public void setUsuApliModi(String usuApliModi) {
		this.usuApliModi = usuApliModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_modi_regi", length = 29)
	public Date getFecModiRegi() {
		return this.fecModiRegi;
	}

	public void setFecModiRegi(Date fecModiRegi) {
		this.fecModiRegi = fecModiRegi;
	}

}
